### ISSUE TITLE
Scroll/Touch offsets the zoomed image's animation's place to return to

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#1]
![demo](https://cloud.githubusercontent.com/assets/592876/16843515/6853435a-49d9-11e6-9363-748bdd9b4425.gif)

**Comment by m90khan** [comment]
Hi, is there a way to change the offset value?

**Comment by rpearce** [comment]
@m90khan This is a 5.5 year old PR, so in the future, I would perhaps start a discussion in the Discussions tab.

To answer your question, yes: the `zoomMargin` parameter, as described in the README.md, will allow you to pass an offset: https://github.com/rpearce/image-zoom#both-uncontrolled--controlled-components

**Comment by m90khan** [comment]
Hey @rpearce: Sorry for posting here. I opened a new issue. Thank you for the code and help.
