### ISSUE TITLE
Uncaught (in promise) Error: ImageZoom.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by ashsepra** [rpearce/react-medium-image-zoom#104]
This issue is a: 

- Question / support request

## Description
For some reason I can't get it to work right, I get an error about
Uncaught (in promise) Error: ImageZoom.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

Cheers,

**Comment by rpearce** [comment]
@ashsepra thank you for using the project! In order to help you, can you please provide a demo project or example of the code you're using?

**Comment by ashsepra** [comment]
Hi @rpearce ,

I think I'm wrong using dependency. Based on my project using ReactJS version 15.x, I'm using version 3.x instead of version 2.x. Not an issue anymore, the component rendered well, good job! I can close it now
Cheers,

**Comment by rpearce** [comment]
Great! No worries
