### ISSUE TITLE
Remove Firefox check and make all browsers behave the same

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#119]
This issue is a: 

- Other

## Description
We should consider taking out the `InstallTrigger` Firefox check and make the same functionality happen across all the browsers. It's probably the safest thing to do.

Conversation Reference:
https://github.com/rpearce/react-medium-image-zoom/pull/117#issuecomment-358774304

Basically, these lines (https://github.com/rpearce/react-medium-image-zoom/blob/master/src/Zoom.js#L87-L92)

```js
const src = img.currentSrc || img.src

// See comment at top of file for Firefox check information
const newState = isFirefox ? { tmpSrc: src } : { src }

this.setState(newState)
```

should be changed to

```js
this.setState({ tmpSrc: img.currentSrc || img.src })
```

and the `isFirefox` check should be removed.

cc @kingdido999 for talking sense into me.

**Comment by HippoDippo** [comment]
I am happy to work/fix this. This will be my first code contribution though.
