### ISSUE TITLE
popstate event/browser back button/forward button should close the zoom

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#12]

**Comment by rpearce** [comment]
This issue comes from folks who don't blow away the DOM structure yet use `pushState` (or a hash URL change) to show a different interface. When you navigate with this and the DOM doesn't remove the `ImageZoom` component, then it doesn't technically know to close.

In the light of day, I wonder if listening to `window.popstate` is actually what is desirable, or if it would be more appropriate for the component to receive an optional boolean value for whether or not it should be open/zoomed:

```js
<ImageZoom
  image={{
    src: 'bridge.jpg',
    alt: 'Golden Gate Bridge',
    className: 'img',
    style: { width: '50em' }
  }}
  zoomImage={{
    src: 'bridge-big.jpg',
    alt: 'Golden Gate Bridge'
  }}
  isZoomed={ false }
/>
```
If that makes more sense, then this could also enable you to trigger an opening/closing of this without having to do a hack like triggering a click to make it close.

Thoughts?

**Comment by jewlofthelotus** [comment]
I definitely like the `isZoomed` option in any case.

**Comment by rpearce** [comment]
@jewlofthelotus can you think of any scenario where clicking the back button _shouldn't_ close the zoom?

**Comment by jewlofthelotus** [comment]
@rpearce does zooming the image currently trigger a hashchange? I don't recall.  If it does, then back should close the zoom. If it doesn't, closing on back doesn't make sense.

**Comment by rpearce** [comment]
@jewlofthelotus No, it does not trigger a hash change. Most folks blow away the DOM structure when using a SPA and the back button, but that other use case exists where you use pushstate/hash change and don't blow it away -- the component isn't unmounted and therefore not closed.

So what I'll take from this is that `isZoomed` should be a feature
