### ISSUE TITLE
shouldRespectMaxDimension doesn't really respect max dimension

### ISSUE THREAD

**Issue by pavelkornev** [rpearce/react-medium-image-zoom#123]
Hi!

First of all, thanks for this great component and all your effort!

But the behavior of ```shouldRespectMaxDimension``` seems to be confusing and strange. When we specify zoomImage, this original image can be still smaller than the actual window size, so, we don't want it to be scaled with transform and want that its original size is being respected.

The current use case of ```shouldRespectMaxDimension``` is valid, but we would expect it to respect original image dimention if there is one.

Are there any technical difficulties for this limitation?

**Comment by rpearce** [comment]
@pavelkornev (I'm on my honeymoon but should have a little time here and there)

For `shouldRespectMaxDimension`, the docs state,

> When `true`, don't make the zoomed image's dimensions larger than the original dimensions. Only supported if no `zoomImage` is provided. Will also disable the zooming if the image's is already rendered at its maximum width & height.

To clarify, are you saying you're passing a `zoomImage` along with `shouldRespectMaxDimension` (which, as you know, is not supported) and want the original to not exceed its dimensions when "zooming"?

__Can you provide an example of the issue so that I can understand this more thoroughly?__ This can be a fork of this repository that I can clone that demonstrates the issue.

**Comment by pavelkornev** [comment]
> To clarify, are you saying you're passing a zoomImage along with shouldRespectMaxDimension (which, as you know, is not supported) and want the original to not exceed its dimensions when "zooming"?

Exactly. That's why I'm not saying that it is a bug. My question is, what is a reason for this decision?

> Can you provide an example of the issue so that I can understand this more thoroughly? This can be a fork of this repository that I can clone that demonstrates the issue.

It's not a technical issue, but a visual one. When an image scales more than its size, the image is simply blurred. Do we really need an example for this?


PS. I can send a PR if you decide to change this behavior and make ```shouldRespectMaxDimension``` work even if ```zoomImage``` is specified.

**Comment by rpearce** [comment]
@pavelkornev There wasn't a use-case before on other projects for having `shouldRespectMaxDimension` work with a `zoomImage`, but it seems there now is!

PR(s) and feedback on the process are always welcome. This tool should make your life easier, and if it doesn't, then there's discussion to be had (as we are now). Thanks again for investing your time in using this

**Comment by rpearce** [comment]
@pavelkornev What would you like to do with this issue? As the usage stated here seems to technically be something that isn't currently supported, are you still interested in contributing and seeing if we can make something work for you?

**Comment by rpearce** [comment]
Closing in favor of potential new issue if this suits.
