### ISSUE TITLE
Wrong images is used after second zoom

### ISSUE THREAD

**Issue by pavelkornev** [rpearce/react-medium-image-zoom#124]
Using v2.0.7 (because our project is still on React v15) our initialization of the component looks like this:
```
<ImageZoom
    shouldReplaceImage={false}
    image={{
        src: 'file1.jpg',
    }}
    zoomImage={{
        src: 'file2.jpg',
    }}
/>
```

When we click on the image for the first time, ```file2.jpg``` is in the zoomed dialog (expected!), then we close it and click it again for zooming and file1.jpg is in the zoomed dialog. Why? Expected behavior: ```file2.jpg``` has to be always rendered in the zoomed dialog.

**Comment by rpearce** [comment]
Pavel,

Thanks for submitting an issue and using the component in general!

I’ve just got married and am on my honeymoon, and I can look at this sometime over the next week.

Until then,
Robert

-- 
Robert Pearce
https://robertwpearce.com
https://www.linkedin.com/in/robertwpearce
m-NZ: +64 20 41305113
m-US: +1 843 568 9080
m-UK: +44 7477 424374

**Comment by rpearce** [comment]
@pavelkornev can you please provide a full example of the issue in a fork or repository somewhere?

If this is an issue, then it surely is a serious one. @joshsloat have you noticed this being a problem?

**Comment by pavelkornev** [comment]
Oh. It would be much more easier if this library supports unpkg.com, then I would be able to do an example just in jsbin without any forks ;-) I'll do an example at earliest possible.

**Comment by rpearce** [comment]
I don't know much about unpkg (except I think Michael Jackson and some folks created it?). What would need to happen to something like https://unpkg.com/react-medium-image-zoom@3.0.10/ to make it support unpkg? If I can do something to help, I'm glad to

**Comment by joshsloat** [comment]
@rpearce - I haven't seen this, but we're also not making use of `zoomImage` in Rise. I did poke at this lightly using the storybook and the `Provide a zoom image` example appears to be working as expected. If we get some solid repo steps on this, I can take a 👀 so you can focus on slightly more important things like your honeymoon :)

**Comment by pavelkornev** [comment]
We updated to React@16 and it's not reproducible with v3.x, only relevant for v2.x. You can decide whether to close it or investigate it further.

@rpearce, you just need to generate a minified version of the library with all bundled dependencies in one file and expose it into a global variable. Example: https://unpkg.com/react-router@4.2.0/umd/, https://stackoverflow.com/a/45807979/280989

**Comment by rpearce** [comment]
@pavelkornev as this is the only reported case of it, I will choose to let that bug stay in the 2.x branch until I hear of it being a problem again (time...).

Meanwhile, I'll create an issue for getting this setup on `unpkg`
