### ISSUE TITLE
Fully support being on unpkg

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#125]
Per commentary [here](https://github.com/rpearce/react-medium-image-zoom/issues/124#issuecomment-368354380) by @pavelkornev, make sure project output is compatible with https://unpkg.com/.

**Comment by 0x6e6562** [comment]
I have a bug I'd like to first reproduce on codepen or similar - it seems quite tricky to load this module without unpkg support.

@pavelkornev Did you have a template for codepen/jsfiddle/jsbin to use to submit issue reproductions?

**Comment by rpearce** [comment]
@0x6e6562 Not at present. Unpkg does not recommend submitting your own repo, which makes this awkward. Historically, I've seen people make dummy repos or copy-paste code, which isn't ideal, but it's gotten the job done thus far.

**Comment by cbothner** [comment]
How about CodeSandbox for bug reports? It uses webpack under the hood so the library doesn't need to do anything special.

https://codesandbox.io/s/wwp7n7rr47

**Comment by rpearce** [comment]
@cbothner for the win. I'm gonna use this for future documentation.

Closing because I don't know much about unpkg, and code sandbox solves the goal.

cc @0x6e6562

**Comment by 0x6e6562** [comment]
@cbothner Perfect! Many thanks for the heads up :-)
