### ISSUE TITLE
After unzoom the image src is replaced by zoomimage src

### ISSUE THREAD

**Issue by 0x111** [rpearce/react-medium-image-zoom#126]
This issue is a: 

- Bug report

## Expected behavior
While using this, I noticed that after I click on an image and then unzoom it, the src of the img tag is replaceted by the `zoomImage` src instead of having the original `image` src set.

## Steps to reproduce behavior
1. Open https://rpearce.github.io/react-medium-image-zoom/
1. Open the dev console and inspect the bridge picture's img element
1. Click on the picture of the bridge, then unzoom it, and inspect the src value changing

## Link to repository/example of behavior
[example](https://rpearce.github.io/react-medium-image-zoom/)

**Comment by 0x111** [comment]
Nevermind, overlooked the docs.

**Comment by rpearce** [comment]
Glad you worked it out!

-- 
Robert Pearce
https://robertwpearce.com
https://www.linkedin.com/in/robertwpearce
m-NZ: +64 20 41305113
m-US: +1 843 568 9080
m-UK: +44 7477 424374
