### ISSUE TITLE
Example for how to background override?

### ISSUE THREAD

**Issue by sgriffey** [rpearce/react-medium-image-zoom#127]
This issue is a: Question

## Expected behavior
I'm hoping to override the defaultStyle of the Overlay background. Could provide a direct example of how to do this? My javascript capabilities are crude. Been trying to include the styling like such. Not having any luck. Thank you.

```
<ImageZoom
          image={{
            src: `${image}`,
            alt: `${alt}`,
            className: `${className}`,
          }}
          zoomImage={{
            src: `${image}`,
            alt: `${alt}`,
            defaultStyles: {
              overlay: { backgroundColor: '#000'}
            }
          }}
/>
```
![image](https://user-images.githubusercontent.com/4163309/39611485-d3acdec4-4f0c-11e8-8e61-0b6841a1b149.png)

**Comment by cbothner** [comment]
This is what I’m doing. defaultStyles is a prop on ImageZoom in and of itself. 

```
<ImageZoom
      defaultStyles={{ overlay: { backgroundColor: '#1D2934' }}}
      image={...}
      zoomImage={...}
    />
```

**Comment by sgriffey** [comment]
@cbothner bless you. that worked. thank you.
