### ISSUE TITLE
Image zoom with route change

### ISSUE THREAD

**Issue by oyeanuj** [rpearce/react-medium-image-zoom#128]
This issue is a: **Feature request**

## Description
Hi @rpearce, firstly, thank you for creating this library. I had a use-case with a slight twist - I am trying to show images (say in, a grid) and then on clicking on one, opening it in a modal but also changing route (to reflect the route of the image in 'full mode'). This is similar to how images in most photo sharing sites or social networks would work.

Now, I understand that the original case was more of Medium's design but I'm wondering if it would be possible somehow to use this library to achieve the behavior described above. So far, the only site which I have seen done that is Invision with their Boards. 

I was a little encouraged on the possibilities by this comment that you made on a different thread -  https://github.com/rpearce/react-medium-image-zoom/issues/116#issuecomment-357806930

I'd appreciate any thoughts or ideas you may have.

**Comment by rpearce** [comment]
@oyeanuj If I understand correctly, it sounds like you want to be able use a URI route to determine whether the image starts off in "full mode" or not. You can manually control this via the `isZoomed` property that is specified in the ["Usage" section of the README](https://github.com/rpearce/react-medium-image-zoom#usage).

The only difference is that you'll now need to maintain the state of `isZoomed` and you can do so by having your state listen to `onUnzoom` (see README) to know when the user does something that would normally trigger an "unzoom".

So again, you need to maintain state yourself and do so by utilizing two props:
* `isZoomed`
* `onUnzoom`

**Comment by cbothner** [comment]
This is what I get for watching this repository... as soon as I saw the email I started thinking about how I would do it, and before I knew it I was writing code 😂

This is how you could use the library in controlled mode to do what you want: https://codesandbox.io/s/z2oj75ryv4

But it doesn’t work perfectly! @rpearce this has revealed the fact that `<ImageZoom>` crashes if we try to mount it in zoomed mode. If you reload into a zoomed route (or follow a link to one https://z2oj75ryv4.codesandbox.io/space) you'll see an error. Do you think it just needs some null checks? Or would it take a re-architecture that might be out of scope? 😧)

@oyeanuj You might be able to work around this by wrapping `<ImageZoom>` with a stateful component that uses `componentDidMount` and `componentDidUpdate` to set `isZoomed` based on the route... https://codesandbox.io/s/2o410jkwnj it’s just a little jumpy on the first load of a zoomed route.

**Comment by rpearce** [comment]
@cbothner Oh noes! It should be able to mount in zoomed mode... what I get for no tests. I reckon I should add a `storybook` example with this and fix the bug in the process -- it seems to be coming from @joshsloat's tab navigation additions, so it could be an easy fix in there.

**Comment by rpearce** [comment]
@oyeanuj @cbothner I've marked this as a `bug` and will try to fix it ASAP. I'll check back in on this issue thread.

**Comment by rpearce** [comment]
@oyeanuj @cbothner this should be resolved in `v3.0.11`.

**Comment by oyeanuj** [comment]
Firstly, wow - I filed the ticket, and didn't check my email for a day and come back to all the comments! Thank you so much @cbothner @rpearce 😄 

I am not sure if it would fully solve my use-case and I think I'm at fault for not explaining it in more detail. I think what I didn't mention explicitly and realize now that I might need - is to understand if the library can support any non-image components?

The reason and I ask, and the reason I was interested in #116 was that, when opened in a modal, I was planning to show more components than just an image - like caption, some controls/textbox etc.

So, it is almost like going the first snippet to the second on route change, but maintaining the zoom animation:

```jsx

// When shown as a thumbnail in an album
<ThumbnailComponent size = "small" onClick = {this.makeBig} >
  <Image src = {smallSrc} />
</ThumbnailComponent>

// TO:

// When shown in Modal
<ThumbnailComponent size = "big" onClick = {this.makeBig} >
  <Image src = {bigSrc} />
  <SomeOtherControl />
  <SomeOtherInfo />
</ThumbnailComponent>
```

Thoughts @cbothner @rpearce ?

**Comment by oyeanuj** [comment]
@rpearce thank you for the answer (and add to the list!). I'll explore other solutions and report back incase I get something to work!

**Comment by rpearce** [comment]
Hi, @oyeanuj! It has been some time since we communicated on this issue. Since `v5.1.x`, you can provide any custom content to the zoom dialog that you like, and you can find a simple example of that here: https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--modal-figure-caption
