### ISSUE TITLE
Handle broken image uri

### ISSUE THREAD

**Issue by serfgy** [rpearce/react-medium-image-zoom#137]
Is there a way to handle broken image uri? In the event the src value leads to an unavailable image, the broken image pic appears and can be unsightly.

Also, clicking on the broken image pic still zooms in on it.

**Comment by serfgy** [comment]
If the image link is broken or picture is not found, how `<Img>` (npm react-image) handles it is that `<img>` will not be rendered, I'm not quite sure how to do this with `<ImageZoom>` but I can share my current workaround:

```
                  <ImageZoom
                    image={{
                      src: window.formAppConfig.imageEntry + '/' + text + '.jpg',
                      style: { margin: "-12px", width: "36px", height: "36px" },
                      onError: (e) => { e.target.src = 'http://xxx.com/1x1.png' } 
                    }}
                  />
```
`onError` works because it's an existing prop of `<img>`, this however does not prevent <ImageZoom> from rendering but instead replaces the broken image (post compile I believe), so if we click on the blank 1x1 image it still zooms out. The best case scenario would be that <ImageZoom> self checks like <Img> and would not render in the first place. 

[https://github.com/mbrevda/react-image/blob/master/src/index.js]

**Comment by serfgy** [comment]
Yea, the priority is to disable the zoom by default for the broken link case, even if we cant stop the rendering for now. Cheers!

**Comment by rpearce** [comment]
K I'll schedule some time for this and get back to it soon. Thanks for your submission, and I'll add you to the All Contributors list in the README

**Comment by rpearce** [comment]
Update: almost done and should have a PR up either tonight or tomorrow

**Comment by serfgy** [comment]
@rpearce , just tested it, it detects failed images and disables the zoom nicely!

I tried removing the timeout and put the src change on the onError instead (on the second image in the storybook) and it also works with no issues:
```
          onError: a => {
            a.target.src = 'https://rpearce.github.io/react-medium-image-zoom/bridge.jpg';
          }
```
Cheers!

**Comment by rpearce** [comment]
Cool. I'll merge it up and notify you when it's published
