### ISSUE TITLE
"Transform: Rotate" styling 

### ISSUE THREAD

**Issue by vtcaregorodtcev** [rpearce/react-medium-image-zoom#144]
This issue is a:  Feature request

## Description
It would be nice If I set 'transform: rotate' image will starting to move from the rotated state, and returning to the same rotated state. Now transform property is replacing by default config. And the image is always starting to move from the not rotated state.

![ezgif com-optimize](https://user-images.githubusercontent.com/24553355/49756999-6900fb00-fccc-11e8-86f1-0e3cc97c4a32.gif)

**Comment by rpearce** [comment]
@vtcaregorodtcev thank you for bringing this issue to light! It is a symptom of a deeper issue that I've not quite sorted out how I want to solve yet as part of https://github.com/rpearce/react-medium-image-zoom/issues/143, but I may be able to fix this for you in the meantime.

When do you need this by? I can't guarantee anything, but it'd be good to know!

**Comment by vtcaregorodtcev** [comment]
@rpearce thank you for fast respond. I guess it can wait for a while, there are no restricted deadlines 👍

**Comment by rpearce** [comment]
@vtcaregorodtcev groovy. I'll put it on my to-do list for this week / next week. I've got a blog post I need to get out the door first and will then look at this.

**Comment by rpearce** [comment]
@vtcaregorodtcev Update: I'm going to be addressing this in next couple of days

**Comment by vtcaregorodtcev** [comment]
@rpearce great, appreciate it!

**Comment by rpearce** [comment]
@vtcaregorodtcev Update: after Xmas! Sorry for the wait!

**Comment by rpearce** [comment]
@vtcaregorodtcev can you send me an example of exactly how you're using this? The `transform` property is being overwritten with `translate3d(0, 0, 0) scale(1)`, and I reckon I can find a way to append to that, but I need to see how you're using it.

**Comment by vtcaregorodtcev** [comment]
@rpearce sure, for example 

https://gist.github.com/vtcaregorodtcev/2428f93e4cf5df501bb1ee0130b7b09d

and if i try to put 
`style: {
      transform: 'rotate(${angle}deg)'
    }`
to `zoomImage` it will be rewrite by default styles.

**Comment by rpearce** [comment]
@vtcaregorodtcev okay, I'll see what I can do... I'm also about to do a whole rewrite of this project, as well. If I can get this fixed in a way that makes sense, I'll be publishing it as a patch-level update. Here we go...

**Comment by rpearce** [comment]
@vtcaregorodtcev It's not looking good without making some sweeping changes. CSS doesn't allow for `transition` to be applied to only one part of a `transform`. The fix would be do apply the `transition` behavior as a CSS class & scope the behaviors to different selectors, but this project currently has _zero_ CSS files & selectors and only uses inline styles. Unless you think you can come up with a fix, I'm not sure I can solve it right now; however, I will 100% design the new version with this in mind.

**Comment by rpearce** [comment]
Update: while the rewrite is not done yet, we are keeping this issue in mind, and this should do the trick for keeping the original `transform` (https://github.com/rpearce/react-medium-image-zoom/blob/master/source/Activated.js#L88-L94).

**Comment by rpearce** [comment]
This should be resolved in the latest v4 alpha version. While that is looking good but not yet stable, I'm going to consider this resolved. Please let me know if you feel differently or find otherwise.
