### ISSUE TITLE
Feature / Support Request - Slideshow

### ISSUE THREAD

**Issue by Daveiano** [rpearce/react-medium-image-zoom#145]
This issue is a kind of both:

- Feature request
- Question / support request

## Description

Is there any possibility or example to implement a Slideshow with this package? I have tried this with a controlled component, but when I set the `isZoomed` property to `false` on one image and to `true` on another image, the open and close animations come into play, doesn't look very nice. 

So my Question: Is there any way to open an Image Slider/Colorbox with this beautiful effect?

**Comment by Daveiano** [comment]
Thanks for the fast answer!

I am struggling to get this to work in e.g. jsfiddle, how can I add react-medium-image-zoom inside the fiddle?

But nonetheless, here is my Code. I have added some buttons for closing the slideshow and a unfinished (does not watch out for last image) next button to test the behavior:

```
import React, { Component } from 'react';

// 3rd Party
import ImageZoom from 'react-medium-image-zoom';

class ImageGallery extends Component {
  state = {
    allowZoom: true,
    countdown: 0.5,
    imageStates: this.props.images.map(() => false),
    showControls: false
  };

  handleUnzoom = () => {
    this.setState({
      allowZoom: false,
      imageStates: this.props.images.map(() => false),
      showControls: false
    });

    setTimeout(
      () => this.setState({ allowZoom: true }),
      this.state.countdown * 1000
    )
  };

  handleZoom = index => {
    if (this.state.allowZoom) {
      const imageStates = this.state.imageStates;

      imageStates[index] = true;

      this.setState({
        allowZoom: false,
        imageStates,
        showControls: true
      });
    }
  };

  handleNext = () => {
    const imageStates = this.state.imageStates,
      nextImageIndex = imageStates.findIndex(image => image === true) +1;

    this.setState({ imageStates: this.props.images.map((e, index) => index === nextImageIndex), });
  };

  // @todo implement throttle
  scrollHandler = () => {
    this.handleUnzoom();
  };

  componentDidMount() {
    window.addEventListener('scroll', this.scrollHandler);
  }

  componentWillUnmount() {
    window.removeEventListener('scroll', this.scrollHandler);
  }

  render() {
    return ([
      <div key={"imageZoom"}>
        {this.props.images.map((item, index) =>
          <div key={index} onClick={() => this.handleZoom(index)} className="gallery-item">
            <ImageZoom
              image={{
                src: item.small,
                className: 'img',
              }}
              shouldReplaceImage={false}
              shouldRespectMaxDimension={true}
              zoomImage={{ src: item.big }}
              isZoomed={this.state.imageStates[index]}
              onUnzoom={() => this.handleUnzoom()}
            />
          </div>
        )}
      </div>,
      <div key={"controls"}>
        {this.state.showControls &&
        <div id="imageZoomControls">
          <div id="imageZoomControls--close" onClick={() => this.handleUnzoom()}>close</div>
          <div id="imageZoomControls--next" onClick={() => this.handleNext()}>next</div>
          <div id="imageZoomControls--prev">prev</div>
        </div>
        }
      </div>
    ]);
  }
}

export default ImageGallery;
```


Mounting Point: 

```
ReactDOM.render(
        <ImageGallery images={[
           {"small": "https://via.placeholder.com/150", "big": "https://via.placeholder.com/500"},
           {"small": "https://via.placeholder.com/150", "big": "https://via.placeholder.com/500"},
           {"small": "https://via.placeholder.com/150", "big": "https://via.placeholder.com/500"}
        ]} />,
        document.querySelector('#app')
      );
```

CSS:

```
#imageZoomControls--close{
  position: fixed;
  z-index: 1050;
  top: 50px;
  left: 50%;
  color: black;
}

#imageZoomControls--next{
  position: fixed;
  z-index: 1050;
  top: 50%;
  right: 50px;
  color: black;
}
```

**Comment by Daveiano** [comment]
@rpearce It would be very nice if I could solve this issue by the end of the year. But nobody's life depends on it ;)

**Comment by rpearce** [comment]
@Daveiano got it. It's on my to-do list, along with completely refactoring this entire project :)

**Comment by Daveiano** [comment]
@rpearce Oh well :D 

I will also try to look at this again when I got some time. Thank you very much for taking the time!

**Comment by rpearce** [comment]
@Daveiano Update: after Xmas! Sorry for the wait!

**Comment by Daveiano** [comment]
Don't stress yourself, merry Xmas!

**Comment by rpearce** [comment]
@Daveiano could you describe what sort of slideshow you're trying to do, exactly? Is it like a normal one that sits on the page and cycles through them? What is supposed to be happening? Is it supposed to be like a Bootstrap slider but with this image zoom effect? The example provided, after looking over the code and trying it out, isn't quite clear to me.

**Comment by Daveiano** [comment]
Here is webpage I am working on (work in progress, it's not in production), there is the exact code I posted in action.

http://www.fuer-angie.net/der-haselhof

If you click on the first image (with the horses) and the on "next", the next image (the dog) shows up and disappears. What I am doing if you press on next, I remove the `isZoomed `state from the horse image and add it to the dog image.  

What I want is a Colorbox (sorry I said slideshow), for example like http://simplelightbox.com/, but with the opeeing animation of this project.

I hope it is more clear now what I want?

**Comment by Daveiano** [comment]
I managed to get this to work:

My problem was the `onUnzoom` function which was triggered when the `isZoomed` state changed on the images. i have removed the part `onUnzoom={() => this.handleUnzoom()}` from my `<ImageZoom /> `Components.

You can see a working version under the link I shared in the previous post.

**Comment by rpearce** [comment]
Ah! That's great news. In the next version I'm working on, I'll consider including an option to disable the animation (may make the slideshow work better).

**Comment by Daveiano** [comment]
This would be a great addition! But just when changing the image, not on opening.

And thank you for your support!

**Comment by javialeung** [comment]
Any updates on this? I also implemented something similar to Daveiano. It would be good to disable the animation!

**Comment by rpearce** [comment]
@javialeung Honestly, I haven't put much thought into it. I think I know how to make this happen, so I'll reopen this while I think about it!

**Comment by javialeung** [comment]
Thanks for the update! I appreciate the support for this.

The slideshow I have works great with the image zoom it's just the animation when changing images is causing a not so great user experience.

**Comment by rpearce** [comment]
@javialeung what I'm going to look at this weekend is seeing if we can provide an animation config flag (some people might not want the animation for accessibility reasons sometimes) that will set the `transition-duration` to `0` or remove the `transition-duration` property entirely.

**Comment by rpearce** [comment]
@Daveiano @javialeung Looks like I already did this! As you can see in the [readme's API section](https://github.com/rpearce/react-medium-image-zoom#api), you can pass a `transitionDuration`, which will disable the transition.

You can pair this with the [controlled component](https://github.com/rpearce/react-medium-image-zoom#controlled-component-controlled) and listen to the document for arrow keys in order to make this happen.

As a bonus, I created an example in the Storybook examples for you! https://rpearce.github.io/react-medium-image-zoom/?path=/story/react-medium-image-zoom--image-gallery-slideshow-style-images

**Comment by Daveiano** [comment]
@rpearce Thank you very much for response!

I will look into this in the next few days and give feedback! Thanks a lot.
