### ISSUE TITLE
Default classes for DIV elements

### ISSUE THREAD

**Issue by dsone** [rpearce/react-medium-image-zoom#147]
This issue is a: "Feature" request

## Description
Currently, there are three DIV elements added to the body on zoom and you have no clue what DIV is the overlay/zoomContainer.
That leads to issues similar to https://github.com/rpearce/react-medium-image-zoom/issues/127.
I was using the _zoomContainer_ for custom styling, thinking that was the right one. Apparently, it wasn't.

It would be nice if the DIV containers would contain default class names. This would make it so much easier to do basic styling outside of the provided options of the package itself and support better understanding of what is added into the DOM.

**Comment by rpearce** [comment]
Hi @dsone, thank you for voicing your concern! Let's see if I can address all the things.

* * *

> Currently, there are three DIV elements added to the body on zoom and you have no clue what DIV is the overlay/zoomContainer.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/592876/54090012-3c947200-43d4-11e9-9c6f-7328c005cf81.png">

At the moment, those first two are there for nothing more than React rendering purposes and hanging on to some events (probably could be done better). The one that is highlighted is the fixed container, and the `div` that is a sibling to `img` is the overlay.

* * *

> It would be nice if the DIV containers would contain default class names. This would make it so much easier to do basic styling outside of the provided options of the package itself and support better understanding of what is added into the DOM.

While adding classnames specific to this library is not something I think is a good idea for a component, perhaps adjusting the API in the [rewrite](https://github.com/rpearce/react-medium-image-zoom/issues/143) (which I've not gotten back to but is on [my list of priorities](https://github.com/users/rpearce/projects/1)) to encourage clear, fine-grained control is something I can think on as it gets rewritten.

* * *

As far as the `image` and `zoomImage` stand, at present you can pass them your own `className` props, and for control over the overlay and even more, you can pass `defaultStyles` to override [these styles](https://github.com/rpearce/react-medium-image-zoom/blob/master/src/defaults.js#L8-L38)

* * *

I'll keep this issue open until the rewrite occurs.

**Comment by rpearce** [comment]
Hi, we're not done with the rewrite yet, but we are keeping this in mind for the following rewrite issue: https://github.com/rpearce/react-medium-image-zoom/issues/165.

**Comment by rpearce** [comment]
As you can see when inspecting a zoomed image here, https://rpearce.github.io/react-medium-image-zoom/?path=/story/react-medium-image-zoom--with-img, we are using some class names for static styling (see image):

<img width="785" alt="image" src="https://user-images.githubusercontent.com/592876/71053682-27105d80-2147-11ea-9acf-7b0492c15f15.png">

[The API for v4](https://github.com/rpearce/react-medium-image-zoom#api) allows for:
* overlay background starting color (before transition)
* overlay background ending color (after transition)
* animation transition duration
* ability to set the `zoomMargin`
* ability to pass a `wrapStyle` object to add some last-minute styles to the top-level `div` that we use to wrap the other components

While `v4` is still in `alpha`, I'm going to close this PR, for I believe it has been addressed there and will help to clean up the board. If you feel differently, please let me know.
