### ISSUE TITLE
preventDefault on Escape

### ISSUE THREAD

**Issue by jorilallo** [rpearce/react-medium-image-zoom#148]
- Feature request

## Description

It would be nice if Escape keypress would be `preventDefault`'d. We have some logic in the container that holds RMIZ for Escape and when closing the image, both trigger Not sure if there's downsides.

**Comment by rpearce** [comment]
@jorilallo Thanks for reporting this! Great point. I'll factor this into the rewrite, unless you would like to make a PR for the current minor version.

**Comment by jorilallo** [comment]
@rpearce no hurry, I'll get around this with className in the meantime. Probably easier if you include in the refactor. Thanks for the great lib, really enjoying it :)

FYI; Not my current project but [Outline](https://github.com/outline/outline) is using this in production

**Comment by rpearce** [comment]
@jorilallo Got it. Also, rock on! 🎉

**Comment by rpearce** [comment]
We're not done with the rewrite, but we're now tracking this issue as a part of the rewrite's issue https://github.com/rpearce/react-medium-image-zoom/issues/168.

**Comment by rpearce** [comment]
Closed in #168, and we're using [`event.stopPropagation`](https://github.com/rpearce/react-medium-image-zoom/blob/9942d87a9f026a80056f5d08178a5327cbd6e75f/source/ControlledActivated.js#L57) to prevent event bubbling.

While `v4` is published in `alpha` stage and isn't fully released yet, I'm going to close this to clear up the issue tracker. Please let me know if you feel differently about it.
