### ISSUE TITLE
Feature Request: Loading States?

### ISSUE THREAD

**Issue by james-ff** [rpearce/react-medium-image-zoom#149]
This issue is a: Feature request

## Description
It would be nice if there were loading states, so that it would be possbile to show a template image or loading component while an image is loading. Or maybe I'm missing some easy way that already exists? Thanks!

**Comment by rpearce** [comment]
@james-ff This sort of event / state callback sounds like a good idea to include in the rewrite (see https://github.com/rpearce/react-medium-image-zoom/issues/143).

I've not been able to dedicate time to the project recently (injury + work), but this is the next big thing on my list to do (my OSS priority board https://github.com/users/rpearce/projects/1/).

Thanks for the suggestion.

**Comment by rpearce** [comment]
With the way we're doing the rewrite, I don't think this will be something the library will handle, and whatever you would normally do in the browser in this situation should suffice.

I'll keep this issue open until we are further along, though.

**Comment by rpearce** [comment]
The way I've done the upcoming `v4`, you can do whatever you want while your image is loading (you do whatever you want), then once you detect that it loads, you merely wrap it in the `<Zoom>` component. So... (pseudo-code):
```js
{isLoading && <Spinner />}
{isLoaded && <Zoom><img src="..." ... /></Zoom>}
```
While `v4` is still in alpha, that should resolve this issue, and I'm going to close this to clean up the issue tracker. If you feel differently about my closing it, please let me know.
