### ISSUE TITLE
Handle closing the zoom on scroll

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#163]
When I click on an image and zoom it
Then I scroll the page
Then I should see the zoomed image smoothly return from whence it came

* * *

When I tap on an image on a mobile device and zoom it
Then I use my finger to scroll the page in any direction (say a 10px drag)
Then I should see the zoomed image smoothly return from whence it came

* * *

It would be sweet if we could make this with a single implementation and not have to specify between mobile and desktop.

* * *

Tangentially related issue that has to do with being able to specify what the actual scroll container is: https://github.com/rpearce/react-medium-image-zoom/issues/136

**Comment by rpearce** [comment]
@spencerfdavis how's this bit going? I did some necessary leg-work and have that merged into master. Happy to pick this up if you need

**Comment by sunmoon-idegu** [comment]
@rpearce 
Hello, is this bug fixed? Because my iPhone is still failing on this one. When zoomed in and scroll, it does not zoom out. Is it my problem. My Zoom component is clean, which means I didn't set any attributes. 

Thank you.

**Comment by rpearce** [comment]
@sunmoon-idegu What version of iPhone and iOS are you using? Have you updated to the latest version of this project?
