### ISSUE TITLE
Handle closing the zoom on ESC

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#168]
Given I have zoomed an image
When I press the escape key
The image should be unzoomed

Tangentially related issue: https://github.com/rpearce/react-medium-image-zoom/issues/148

**Comment by Stereoraj** [comment]
Hi, I would like to work on this issue.

**Comment by dnlnvl** [comment]
Hi, I've made a pull-request to fix this issue!
https://github.com/rpearce/react-medium-image-zoom/pull/169

**Comment by rpearce** [comment]
@Stereoraj, it looks like @dnlnvl has already gotten a pretty good PR up for this one, but by all means check out any other issues on here! https://github.com/rpearce/react-medium-image-zoom/projects/1

**Comment by rpearce** [comment]
Good job, @dnlnvl!
