### ISSUE TITLE
Accept zoomMargin prop and use it in the zoomed style calculation

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#174]
_Note: wait until https://github.com/rpearce/react-medium-image-zoom/pull/173 is merged or branch off of it._

* * *

Given a user supplies a `zoomMargin` prop that is a `number`
When the image is zoomed
Then the zoomed image should be offset from the `window` by that amount at its greatest dimension

* * *

When a user does not supply a `zoomMargin` prop
Then the `zoomMargin` default value should be `0`

**Comment by rpearce** [comment]
I'd like to see if Ton Jo is up for his one. Ton, if you comment here, I'll assign you to it.

**Comment by tonjo007** [comment]
sure Robert, I will take it

**Comment by rpearce** [comment]
That's great! Thanks @tonjo007. Ask any questions you have in the gitter or on this issue

**Comment by rpearce** [comment]
@tonjo007 how's this bit going? I did some necessary leg-work and have that merged into master. I am happy to pick this up if you need me to. If you need guidance, feel free to reach out here or in the gitter channel!

**Comment by rpearce** [comment]
I had some time today, so I went ahead and implemented this in https://github.com/rpearce/react-medium-image-zoom/pull/181
