### ISSUE TITLE
Consider publishing v4 alpha

### ISSUE THREAD

**Issue by seaneking** [rpearce/react-medium-image-zoom#188]
This issue is a: 
- Other

## Description

I know the v4.0 of `react-medium-image-zoom` is flagged as in development and highly unstable, but would there be a possibility of publishing an alpha/canary release? I'd love to help test it, since the v4 of this library is the only thing I found that works for my use-case (wrapping `gatsby-image` in a Medium-like tap-to-zoom cleanly).

**Comment by rpearce** [comment]
@seaneking Tell me if this usage is what works for you right now (this is what's currently done):

```js
import Zoom from 'react-medium-image-zoom'
// ...

<Zoom><img ... /></Zoom>

<Zoom><picture></picture></Zoom>

<figure>
  <Zoom><img ... /></Zoom>
  <figcaption>My caption</figcaption>
</figure>
```
and then there are options that you can see used here in the storybook examples (they're also in the README):
https://github.com/rpearce/react-medium-image-zoom/blob/8befc746e234174a5464be29594eabd41e474d33/stories.js#L38-L98

You can also test it out here: https://rpearce.github.io/react-medium-image-zoom/.

* * *

Does that, in its current state, work for you?

And an FYI: the next thing that is in progress on [the board](https://github.com/rpearce/react-medium-image-zoom/projects/1) is doing a "controlled" component (versus the default "uncontrolled" component).

**Comment by rpearce** [comment]
@seaneking I've published [`react-medium-image-zoom@alpha`](https://www.npmjs.com/package/react-medium-image-zoom/v/4.0.0-alpha.0) that you can start trying to use.

Please join on gitter (https://gitter.im/react-medium-image-zoom/community) if you have any general feedback bits you'd like to chat about, or open another issue here :+1:

**Comment by rpearce** [comment]
Oh, and I've also added you to the all contributors list!
<img width="464" alt="image" src="https://user-images.githubusercontent.com/592876/70257430-2d372f00-1782-11ea-839b-8fe13ad6c7b2.png">

**Comment by seaneking** [comment]
Amazing! Thanks @rpearce 

Yep that usage works well. The basic issue with other libraries is that `gatsby-image` doesn’t give you clean access to the underlying `<img />`, since it wraps that up with progressive loading logic etc etc. So `react-medium-image-zoom`s ability to zoom arbitrary elements is ace 👌 

I’ll spin the alpha up soon!

**Comment by rpearce** [comment]
Hi, @madeleineostoja and anyone else! Since `v5.1.x`, you can provide any custom content to the zoom dialog that you like, and you can find a simple example of that here: https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--modal-figure-caption
