### ISSUE TITLE
z-index of zoomContainer should be customizable 

### ISSUE THREAD

**Issue by rsaccon** [rpearce/react-medium-image-zoom#21]
when using UI frameworks I prefer to set the z-index in react-medium-image-zoom to a value higher than the highest z-index used in the UI framework. Messing around with z-indexes in the UI framework itself, can quickly turn into a disaster.

So if the z-index would be exposed as a prop, it would be even easier !!! I have currently to use the source version of react-medium-image-zoom, just for being able to customize the z-index.

**Comment by rpearce** [comment]
If I am understanding correctly, are you saying that you'd like to set the `z-index` on the image and/or the zoomed image? If so, you can set the `style` property with `z-index` like this:
```js
<ImageZoom
  image={{
    src: 'bridge.jpg',
    alt: 'Golden Gate Bridge',
    className: 'img'
  }}
  zoomImage={{
    src: 'bridge-big.jpg',
    alt: 'Golden Gate Bridge',
    className: 'img--zoomed',
    style: {
      zIndex: '8675309'
    }
  }}
/>
```
Does this solve your problem?

**Comment by rpearce** [comment]
To elaborate further, the library provides a few defaults, but almost all of the defaults can be overridden by passing in what you need like I showed above.

**Comment by rsaccon** [comment]
thanks, but let me explain better my issue: I want to set the [zIndex of the zoomContainer](https://github.com/rpearce/react-medium-image-zoom/blob/master/src/react-medium-image-zoom.js#L27) (which is responsible of overlaying all the browser window, I think), and you showed above how to set a zIndex on the image or zoomImage. So how can I override that zIndex?

**Comment by rpearce** [comment]
@rsaccon Makes sense. I'm working on a way to override _all_ the default styles right now, so give me a few!

**Comment by rpearce** [comment]
@rsaccon Go ahead and update to version `0.6.0`. You can now pass `defaultStyles` to override any of the default styles.
```js
<ImageZoom
  image={{
    src: 'bridge.jpg',
    alt: 'Golden Gate Bridge',
    className: 'img'
  }}
  zoomImage={{
    src: 'bridge-big.jpg',
    alt: 'Golden Gate Bridge',
    className: 'img--zoomed'
  }}
  defaultStyles={{
    zoomContainer: {
      zIndex: 8675309
    }
  }}
/>
```

**Comment by rsaccon** [comment]
Great, thanks, works perfect!
