### ISSUE TITLE
Prod build: can't zoom + weird small button

### ISSUE THREAD

**Issue by davalapar** [rpearce/react-medium-image-zoom#212]
# Bug report

## Expected behavior
- It should work okay

## Actual behavior
- It works on dev but not on production build.
- Prod build got webpack tree shaking with terser (not sure if useful info).

## Steps to reproduce behavior
```
// imports
import Zoom from 'react-medium-image-zoom';
import 'react-medium-image-zoom/dist/styles.css';

// then somewhere in the render:
<Zoom wrapStyle={{ width: '100%' }}>
  <img
    alt={title}
    src={image}
    width="100%"
  />
</Zoom>
```

## Example of behavior

- Here nothing happens if you click the button and the image

![image](https://user-images.githubusercontent.com/41451953/72676957-f159ee00-3ad1-11ea-80ad-f76fcda8b761.png)

- The element structure looks like the following on chrome dev tools

![image](https://user-images.githubusercontent.com/41451953/72677001-82c96000-3ad2-11ea-93e5-bb899104cc16.png)

**Comment by rpearce** [comment]
@davalapar It looks like the CSS is not being included in your build. I will try to recreate this tonight, but if you are able to put a simple example together with your build system that reproduced the problem, I'll be able to track it down faster!

**Comment by rpearce** [comment]
FYI: I've just tried it out on a brand new `create-react-app` project, and it looks like it works in development and in the production build there.

**Comment by davalapar** [comment]
Hey man, thanks for the fast response. Turns out you're right the CSS was just not being included properly by our bundler. Thank you very much!

**Comment by rpearce** [comment]
@davalapar there's a related issue that I'm about to resolve that you should know about: https://github.com/rpearce/react-medium-image-zoom/issues/202#issuecomment-577149834

**Comment by rpearce** [comment]
@davalapar i've added you to the all-contributors list in the README! Thanks for your contribution.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/592876/72898089-581e1800-3d1b-11ea-9fe7-f553b89137f7.png">
