### ISSUE TITLE
Smarter detection for image `naturalWidth` and `naturalHeight`

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#213]
Smarter detection for image `naturalWidth` and `naturalHeight` so we don't try to zoom anything when it's already at its maximum dimensions. This would also re-enable the ability to not zoom beyond a source image's natural dimensions once zoomed.

In v3, there was a flag, `shouldRespectMaxDimension`, but I think that should be the default for image-based `children`.

Also, just like v3, if it's already the full-width of the page (or container?), don't zoom it.

**Comment by rpearce** [comment]
Will get :eyes: on this this week

**Comment by rpearce** [comment]
FYI I'm almost done completely rewriting this library into:
1. a vanilla JS package that is ~3kb (minified & gzipped)
1. a react hook that uses 👆  and is maybe 100-150 bytes 

This and all the other issues should be closed out by it. I'm _almost_ there (working out some API stuff).

Thanks for your patience

**Comment by tommoor** [comment]
I'm stuck back on v3 until this lands, is it worth PRing something for v4 or does the ongoing rewrite make it a waste of time? :)

**Comment by rpearce** [comment]
I wouldn't bother with trying anything like that with `v4`, for the fundamental concept of `v4`, "zoom anything", was flawed.

`v5` is going to pull that back to images.

You can read more about the plight here: https://github.com/rpearce/image-zoom/discussions/274

**Comment by tommoor** [comment]
Ahhh, thanks for the link, I hadn't looked in discussions. One thing that I did like about the idea behind v4 was that it would potentially allow us to put information such as a caption underneath the image, or potentially `<` `>`  buttons to navigate a set – just something to think about as you design the v5 API.

Many thanks

**Comment by rpearce** [comment]
@tommoor Nothing is set for `v5` apart from some core things that _need_ to happen (fixing pixelation on iOS and accessibility, for example).

I'm not yet saying I will support what you're asking about, but I would love to know what your use case is so that I can identify how that might fit in. For example, I love what [the New York Times has done](https://www.nytimes.com/2021/03/11/arts/design/what-is-an-nft.html).

**Comment by tommoor** [comment]
Use case is a [https://github.com/outline/rich-markdown-editor](rich text editor) with user-editable captions. The NYT design is great you're right, would certainly be nice to have something with that much panaché

**Comment by madeleineostoja** [comment]
I'll also echo @tommoor, not being able to include non-image things in the zoom would be a dealbreaker for me, and it's the whole reason I used this library over others. My particular use-case is showing a title under the image when it's zoomed, like a more traditional lightbox might. I'm also using the controlled mode to only show the title when it's zoomed. The problem of course is that the zoom also blows the title up with the scale transform, not sure how to solve that one...

**Comment by rpearce** [comment]
@madeleineostoja I'll make sure to bake a caption option in.

Could you further explain what you mean by this?

> Could we perhaps get access to the zoom factor when in controlled mode, so we can account for it in anything that shouldn't be scaled up?

**Comment by rpearce** [comment]
I've got this covered in the next major version I'm working on. Update here: https://github.com/rpearce/image-zoom/discussions/274#discussioncomment-1616865

**Comment by rpearce** [comment]
Here's the latest update on the work that will include this! https://github.com/rpearce/react-medium-image-zoom/discussions/274#discussioncomment-2946565

**Comment by rpearce** [comment]
Hi! Here's a screencast of the max dimension being respected in the `v5-dev` branch:

https://user-images.githubusercontent.com/592876/178144497-df089cd7-1591-455a-8e1c-84f5157c12d0.mp4

Once `v5.0` is released (hopefully not _too_ much longer), I'll see about adding in proper captions and maybe do so by looking for a `<figcaption>` or `[data-rmiz-caption]` (plan for a `v5.1` release)

**Comment by tommoor** [comment]
Your hard work is appreciated 🙏

**Comment by rpearce** [comment]
If anyeone finds some spare time and wants to give the latest build a whirl to try this out:

```sh
npm i --save react-medium-image-zoom@5.0.0-beta2.6
```

And, if you aren't already,

```jsx
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

// ... your other code

<Zoom>
  <MyImage />
</Zoom>
```

The updated [`v5-dev` README is here](https://github.com/rpearce/react-medium-image-zoom/tree/v5-dev#react-medium-image-zoom), and there are some breaking changes to the extra options passed to be aware of, if you're using the options.

Thanks for your time!

**Comment by rpearce** [comment]
Should be closed now with the release of `5.0.0`

**Comment by rpearce** [comment]
@tommoor @madeleineostoja 

Hi! I'm working on adding a feature that includes captioning (adding whatever you want to the zoom state). Do you have any thoughts on this approach? https://github.com/rpearce/react-medium-image-zoom/issues/332#issuecomment-1207252231

**Comment by tommoor** [comment]
Example looks good and would certainly work for our usecase. I would consider just passing an `unZoom`/`onClose` button as prop to custom component rather than a rendered button.

**Comment by rpearce** [comment]
@tommoor Good call on that line of thinking! I'll ponder it and see where that goes.
