### ISSUE TITLE
Component dissapears in Next.js when styles are included

### ISSUE THREAD

**Issue by talentlessguy** [rpearce/react-medium-image-zoom#218]
# Description

When I include styles into `_app.js` the whole component dissapears.

related #202 #165

my app looks like this:

```js
import React from 'react'
import Router from 'next/router'

// Global styles

import '../styles/main.css'
import '../styles/Category.css'
import 'react-tabs/style/react-tabs.css'
import '../styles/main.css'
// included here
import 'react-medium-image-zoom/dist/styles.css'

const App = ({ Component, pageProps }) => {

  return (
      <Component {...pageProps} />
  )
}

export default App
```

image markup isn't even being rendered:

![image](https://user-images.githubusercontent.com/35937217/74862865-e824a100-535d-11ea-8acb-169329224e67.png)

**Comment by rpearce** [comment]
@talentlessguy I'm guessing you sorted it out? Was it anything worth sharing with anyone who might have a similar issue?

**Comment by talentlessguy** [comment]
@rpearce yes, I was using v3 and then noticed that I should switch to v4, and it worked

**Comment by rpearce** [comment]
I understand! v4 is a total rewrite with 100% breaking changes, so that makes sense
