### ISSUE TITLE
TypeScript type definitions on DefinitelyTyped are outdated

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/react-medium-image-zoom#219]
This issue is a: 

- Bug report

I see this project is not developed using TypeScript and [current type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-medium-image-zoom/index.d.ts) are supplied via DefinitelyTyped so this issue is a long shot. Just dropping it here hoping a TypeScript wizard has time to update the type definitions.

## Expected behavior
I expected running `npm install @types/react-medium-image-zoom --save-dev` would install type definitions for version 4.

## Actual behavior
What actually happened was type definitions for version 3 were installed.

Thanks for the amazing component!

**Comment by rpearce** [comment]
@sunknudsen I'm learning TS at the moment and want to try updating the project to use TS, but I am not knowledgeable enough at the moment to accomplish the project update.

Would it be better if this project included an `index.d.ts`?

This doesn't seem _too_ hard, though? The [API](https://github.com/rpearce/react-medium-image-zoom#both-uncontrolled--controlled-components) in the README includes most of the information already.

**Comment by sunknudsen** [comment]
> I'm learning TS at the moment and want to try updating the project to use TS, but I am not knowledgeable enough at the moment to accomplish the project update.

Amazing! Just learned it myself (over the past few months) and never looking back. I don’t have a ton of time available but can help debug TS issues and/or help with code reviews (although admittedly I’m no TS wizard).

> Would it be better if this project included an index.d.ts?

For sure... DefinitelyTyped is for projects that are not (will never be) ported to TypeScript.

**Comment by rpearce** [comment]
Rock on. Where would the best place for an `index.d.ts` file to live? The `main` and `module` fields in `package.json` point to `dist/cjs/index.js` and `dist/esm/index.js` (https://github.com/rpearce/react-medium-image-zoom/blob/master/package.json#L5-L6), would it be better if that file were in the distributed `dist/` folder? Or would it be better at the project root?

There are also _two_ components now exported from here: `Uncontrolled` (the default) and `Controlled`. Does that mean we would need two definition files?

**Comment by sunknudsen** [comment]
> Where would the best place for an index.d.ts file to live?

I believe the `.d.ts` and `.js.map` files should sit beside their parent `.js` files in `dist/cjs/` and `dist/esm/`.

> Does that mean we would need two definition files?

I believe so. That’s how TypeScript does it internally when `declaration` is set to `true` in `tsconfig.json`.

See https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by rpearce** [comment]
Thanks for that link. Here are the best two paths forward for this issue:
* Have someone else fix the immediate issue somehow in DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-medium-image-zoom/index.d.ts)
* Convert project to TypeScript (which won't be too hard... I just need to see how to do this with React; https://github.com/rpearce/react-medium-image-zoom/issues/220) and output `.d.ts` and map files (we're already outputting sourcemaps). It makes sense for this to be my next focus over other little improvements, though I can't say how long this will take.

**Comment by sunknudsen** [comment]
Sounds good @rpearce. For the time being, I used `//@ts-ignore` to patch things up. Looking forward to either option making its way to production.

```typescript
//@ts-ignore
import Zoom from "react-medium-image-zoom"
```

**Comment by dougg0k** [comment]
@rpearce This could help https://github.com/microsoft/TypeScript-React-Conversion-Guide

**Comment by rpearce** [comment]
Thanks @dougg0k

**Comment by rpearce** [comment]
closed via https://github.com/rpearce/react-medium-image-zoom/pull/235

**Comment by rpearce** [comment]
available in `4.2.0`
