### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by MohammedFaragallah** [rpearce/react-medium-image-zoom#226]
After releasing patch 4.0.2 bundle size grow to 160kb 
I'm importing as suggested in the readme

import Zoom from 'react-medium-image-zoom';

https://bundlephobia.com/result?p=react-medium-image-zoom

any idea what's wrong and Thank you for this awesome library.

**Comment by rpearce** [comment]
The size of the NPM package size is due to the `dist/cjs/react-medium-image-zoom.min.js` and `dist/umd/react-medium-image-zoom.min.js`, which are intended for standalone usage in commonjs & browser scenarios, respectively. The number specified there also includes `.js.map` files, which are a fair bit bigger than the actual source files, themselves.

The actual components you would use weigh in ~12kb.

Here are a few questions:
* Are you using commonjs, esmodules, or otherwise?
* Are you including sourcemaps in your build?
* Can you reproduce this in an example repository and share it with me? Without an example, this will be wildly difficult to help with!

**Comment by MohammedFaragallah** [comment]
I reproduced the issue here https://github.com/MohammedFaragallah/zoomrepro
clean CRA installation with just react-medium-image-zoom 

![7731d0a5-0f9b-48db-8abc-5e64e924a5e0](https://user-images.githubusercontent.com/14910456/75691179-9f99ab80-5cac-11ea-899f-108d98af0d58.png)

**Comment by rpearce** [comment]
Cool. Thank you! I'll check it out and see what the issue is outside of my normal working hours (no time right now)

**Comment by rpearce** [comment]
:eyes:

**Comment by rpearce** [comment]
I had to remove `cross-env` from [the `build` command](https://github.com/MohammedFaragallah/zoomrepro/blob/master/package.json#L22), since it is not listed as a development dependency, but I am not seeing the bundle size grow to 160kb. Look below:
```
λ yarn build
yarn run v1.22.0
$ GENERATE_SOURCEMAP=false yarn run build:dev
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  82.63 KB  build/static/js/2.441b531f.chunk.js
  730 B     build/static/js/runtime-main.39048dc8.js
  618 B     build/static/js/main.aaa3124f.chunk.js
  512 B     build/static/css/main.5e3647ae.chunk.css
  384 B     build/static/css/2.b1392919.chunk.css
```
What do I need to do to reproduce the problem?

**Comment by MohammedFaragallah** [comment]
I used source-map-explorer to analyze the bundle using analyze command and it seems to be mistaken but using the build command you used after adding react-medium-image-zoom it adds around 42kb

```
File sizes after gzip:

  387.89 KB (-3 B)      build\static\js\5.9601a09b.chunk.js
  207.5 KB (+40.82 KB)  build\static\js\3.9b53b747.chunk.js
  198.5 KB (+1.51 KB)   build\static\js\2.12c2ac41.chunk.js
  49.14 KB (+35 B)      build\static\js\4.a2f842f4.chunk.js
  27.95 KB (+77 B)      build\static\js\main.1eb49b47.chunk.js
  1.82 KB               build\static\css\4.e10869f1.chunk.css
  1.63 KB (-2 B)        build\static\js\6.e526e22b.chunk.js
  1.48 KB (+13 B)       build\static\js\runtime-main.59363942.js
  384 B                 build\static\css\3.b1392919.chunk.css
```

**Comment by MohammedFaragallah** [comment]
to reproduce 

1. clean CRA installation
2. build to save clean bundle stats
3. add/import react-medium-image-zoom
4. build again to see the difference

I updated the repo

**Comment by rpearce** [comment]
What is the output that you are seeing when you build?

**Comment by rpearce** [comment]
I cloned the repository again, ran `yarn build`, and here is what I see:
```
λ yarn build
yarn run v1.22.0
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  82.67 KB  build/static/js/2.441b531f.chunk.js
  774 B     build/static/js/runtime-main.39048dc8.js
  657 B     build/static/js/main.aaa3124f.chunk.js
  556 B     build/static/css/main.d1b05096.chunk.css
  431 B     build/static/css/2.b3ff1c62.chunk.css
```
I still don't see the 160kb...

**Comment by rpearce** [comment]
Removing `react-medium-image-zoom` yields this:
```
λ yarn build
yarn run v1.22.0
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  39.39 KB (-43.29 KB)  build/static/js/2.70945be3.chunk.js
  774 B                 build/static/js/runtime-main.39048dc8.js
  637 B (-20 B)         build/static/js/main.f06518de.chunk.js
  556 B                 build/static/css/main.d1b05096.chunk.css
  431 B                 build/static/css/2.b3ff1c62.chunk.css
```
So, it does look like there is `43.29kb`, which does seem kind of big, so I can look into that.

**Comment by MohammedFaragallah** [comment]
> I used source-map-explorer to analyze the bundle using analyze command and it seems to be mistaken

You are right its not 160 its 42 sorry about this misunderstanding

> to reproduce
> 
> 1. clean CRA installation
> 2. build to save clean bundle stats
> 3. add/import react-medium-image-zoom
> 4. build again to see the difference

**Comment by rpearce** [comment]
Ah. No worries. I'll look into making that smaller

**Comment by rpearce** [comment]
Initial results look promising: https://bundlephobia.com/result?p=react-medium-image-zoom@4.1.0-alpha.0

<img width="810" alt="image" src="https://user-images.githubusercontent.com/592876/75890506-7a1bb780-5dfc-11ea-86b6-512677c65763.png">

**Comment by MohammedFaragallah** [comment]
Great, please let me not if you need any help.

**Comment by rpearce** [comment]
But I also broke the component in doing that, so yeah. I'll get there.

The react-medium-image-zoom code for a given component with the `helpers` code comes to ~12KiB + 4KiB for CSS, which can then be gzipped down to a good size. There are also a couple of dependencies (`prop-types` will go away in a future release and save us ~5KiB), but overall this is as far as I can get it for now.

**Comment by rpearce** [comment]
https://github.com/rpearce/react-medium-image-zoom/pull/232

  * [before: `390.7kB` Minified; `118.5kB Minified` + Gzipped](https://bundlephobia.com/result?p=react-medium-image-zoom@4.0.4)
  * [after `18kB` Minified; `5.6kB` Minified + Gzipped](https://bundlephobia.com/result?p=react-medium-image-zoom@4.1.0-alpha.1)

There are some more optimizations that could be made by not relying on `react-use`, but that's for another day.

**Comment by rpearce** [comment]
This will be going out in `4.1.0` momentarily
