### ISSUE TITLE
React Portal is incompatible with SSR

### ISSUE THREAD

**Issue by dougg0k** [rpearce/react-medium-image-zoom#229]
Hi,

I've been using _react-medium-image-zoom_ in a Gatsby project and while in development it has been working, it doesnt when you try to build your project.

```
 ERROR #95312 

"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  68 |     overlayBgColorStart: overlayBgColorStart,
  69 |     parentRef: wrapRef,
> 70 |     portalEl: portalEl || document.body,
     | ^
  71 |     scrollableEl: scrollableEl || window,
  72 |     transitionDuration: transitionDuration,
  73 |     zoomMargin: zoomMargin,


  WebpackError: ReferenceError: document is not defined
  
  - Controlled.js:70 Controlled
    node_modules/react-medium-image-zoom/dist/esm/Controlled.js:70:1

```
Btw, I am using the Uncontrolled Zoom.

I found these 2 packages, that could help:
- https://github.com/alex-cory/react-useportal
- https://github.com/jesstelford/react-portal-universal

But there is another possible solution that you would need to ask the consumer to also install this package if he/she were to use _react-medium-image-zoom_ in Gatsby https://www.gatsbyjs.org/packages/gatsby-plugin-portal/

**Comment by rpearce** [comment]
Are you sure you're using the `Uncontrolled` (default) component?
```
- Controlled.js:70 Controlled
    node_modules/react-medium-image-zoom/dist/esm/Controlled.js:70:1
```
Besides that, yeah that makes sense that this would fail, for `document` isn't defined at that point. I'll see about a fix by safely calling `document.body`. If you want to be a real champion here, providing a test gatsby project would be real helpful.

**Comment by dougg0k** [comment]
This is how I am importing, so accordingly to the docs, yes.
`import Zoom from "react-medium-image-zoom";`

**Comment by dougg0k** [comment]
Nevermind, I had a controlled zoom imported somewhere else I had forgotten about.

**Comment by rpearce** [comment]
No worries. Still, it's an issue.

**Comment by rpearce** [comment]
Do you have an example app that reproduces the SSR issue that I can test with?

**Comment by dougg0k** [comment]
I dont, but maybe just a stater gatsby project could be enough. I was just fixing other build issues, there is a few issues happening probably unrelated to the react-medium-image-zoom, but while doing so, the Uncontrolled Zoom didn't affect the build process, but also doesn't work afterwards and I get no errors. 

I'm not sure if these other issues could be affecting it or not, because where these other issues didnt happen in a similar previous project, it did now. I will continue try to find out what is causing and let you know, if there is relation to it or not.

**Comment by rpearce** [comment]
I'll need to test https://github.com/rpearce/react-medium-image-zoom/pull/231 with gatsby SSR, so TBD.

**Comment by dougg0k** [comment]
So, very bizzare case, the issue was that styled-components was loading the classes but not the styling from the classes in the whole application. I had to change node version and reinstall the packages to get it working. In sum, the Uncontrolled Zoom is working fine and was actually affected by the styling issue here. Maybe it was a cache issue.

Only Controlled Zoom is not working in the build process, re-confirmed.

**Comment by rpearce** [comment]
Gotcha. The same issue _can_ exist for both of them, even if it doesn't right now (it's a logical rendering determination that is the difference at the moment), so I'll try to fix it for both.

**Comment by dougg0k** [comment]
Cool, thanks.

**Comment by rpearce** [comment]
I ended up testing with `react-dom`'s `renderToString` function, which doesn't have a DOM.

**Comment by dougg0k** [comment]
Nice!

**Comment by rpearce** [comment]
This will be out in the next release, and I will check back here to notify when that is out. I'm working on bundle size at the moment.

**Comment by dougg0k** [comment]
Sounds good, most needed part for me was the Uncontrolled Zoom.

**Comment by rpearce** [comment]
@dougg0k you can try it right now with what's coming in the next release with version `4.1.0-alpha.0`.

**Comment by dougg0k** [comment]
@rpearce I have just tried and

```
 ERROR #95312 

"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  225 |   }, []);
  226 |   var wrapType = isChildLoaded ? 'hidden' : 'visible';
> 227 |   var portalElement = portalEl || (document || {}).body;
      | ^
  228 |   var scrollableElement = scrollableEl || window;
  229 |   return React.createElement(StrictMode, null, React.createElement("div", {
  230 |     "data-rmiz-wrap": wrapType,


  WebpackError: ReferenceError: document is not defined
  
  - Controlled.js:227 Controlled
    node_modules/react-medium-image-zoom/dist/esm/Controlled.js:227:1
  
```

**Comment by rpearce** [comment]
Argh. Okay I'll try to figure that out. Sorry for the trouble

**Comment by dougg0k** [comment]
No worries, thanks for trying to get it to work.

**Comment by dougg0k** [comment]
Just to let you know, with the `4.1.0-alpha.0`, the Uncontrolled Zoom also doesnt work with the build.

**Comment by rpearce** [comment]
Got it. Try `4.1.0-alpha.1`

**Comment by dougg0k** [comment]
You got it, it's working.

**Comment by rpearce** [comment]
This will be going out in `4.1.0` momentarily. Thanks for your help! I added you to the allcontributors list in the README

**Comment by dougg0k** [comment]
Cool. Thank you for taking the time. Ok.
