### ISSUE TITLE
How could we handle images wrapped within anchors?

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/react-medium-image-zoom#234]
This issue is a: Question / support request

## Description

I use the following code to wrap images within `ZOOM`.

```typescript
const Image: FunctionComponent<ImageProps> = function(props) {
  let src = getImageSrc(props.assetDirectory, props.relativeUrl, props.src)
  return (
    //@ts-ignore
    <Zoom>
      <img alt={props.alt} src={src} width="100%" />
    </Zoom>
  )
}
```

But when an image is wrapped within an anchor (`a`), the link cannot be clicked because the zoom event predominates (which is expected).

```html
<a href="https://www.youtube.com/watch?v=brGLX_92F5o" rel="noopener noreferrer" target="_blank">
  <div class="Main_wrap__260iu">
    <img alt="Why Macs equipped with the new T2 chip are shitty for hackers - YouTube" src="/static/media/privacy-guides/spoof-anonymize-your-mac-address-and-hostname-automatically-at-boot-on-macos/why-macs-equipped-with-the-new-t2-chip-are-shitty-for-hackers.png" width="100%">
    <button aria-label="Zoom image" class="Shared_trigger__3qcaj Main_btn__3CiJa"></button>
  </div>
</a>
```

Bouncing ideas here... how could we handle this use case?

**Comment by sunknudsen** [comment]
The same occurs when both the anchor and image are wrapped within `ZOOM`.

```html
<div class="Main_wrap__260iu">
  <a href="https://www.youtube.com/watch?v=brGLX_92F5o" rel="noopener noreferrer" target="_blank">
    <img alt="Why Macs equipped with the new T2 chip are shitty for hackers - YouTube" src="/static/media/privacy-guides/spoof-anonymize-your-mac-address-and-hostname-automatically-at-boot-on-macos/why-macs-equipped-with-the-new-t2-chip-are-shitty-for-hackers.png" width="100%">
  </a>
  <button aria-label="Zoom image" class="Shared_trigger__3qcaj Main_btn__3CiJa"></button>
</div>
```

**Comment by rpearce** [comment]
If you have an image inside an anchor, then clicking on that should take you to the link, so I would think you should not wrap image links in a `<Zoom>`.

**Comment by rpearce** [comment]
To clarify, if you're trying to make an abstracted `<Image>` component, perhaps specifying a prop like `hasZoom = true` as a default would allow you to override that and only return the image instead of <zoom>image</zoom>

**Comment by rpearce** [comment]
Also, I highly recommend upgrading to the latest version `4.1.0` for a vastly reduced build size, SSR support, and different access to CSS (through `[data-rmiz-...]` selectors).

**Comment by sunknudsen** [comment]
> If you have an image inside an anchor, then clicking on that should take you to the link, so I would think you should not wrap image links in a <Zoom>.

I agree.

I am using [react-markdown](https://www.npmjs.com/package/react-markdown) to render HTML from markdown and all images are handled using the same logic by default. I can definitively hack around this as you suggested.

I was reflecting on consistent image features vs disabling `ZOOM` for anchored images.

I think the latter is the way to go.

> Also, I highly recommend upgrading to the latest version 4.1.0 for a vastly reduced build size, SSR support, and different access to CSS (through [data-rmiz-...] selectors).

Thanks for the heads up. Done!

**Comment by rpearce** [comment]
I'll keep this in mind for when I work on https://github.com/rpearce/react-medium-image-zoom/issues/213, for this will involve searching the `children` for `img` elements.

This library doesn't actually do _anything_ with images (it used to), which opens up the door for giving that zoom to all sorts of things, but we _do_ need certain things for `img` tags like this.

For example, if someone were using a `<picture>` element inside of an `<a>`, we'd need to find the actual element/elements that is an image, traverse up from there and look for an `<a>`, and _then_ tell the library to disable itself. At the moment, I believe it's easier for the consumer to determine what should be zoomable and what should not be rather than have me guess at it.

**Comment by sunknudsen** [comment]
@rpearce After giving it some thought, I am on your side... images within anchors should not have `ZOOM` handler. I think we can close this issue. What do you think?
