### ISSUE TITLE
Adding an option to wrap ZOOM children in span vs div

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/react-medium-image-zoom#236]
This issue is a: Feature request 

## Description

**Not sure this is a good idea (I prefer using a `div` conceptually), but here’s why I’m asking.**

When implementing `react-medium-image-zoom` within a [markdown-to-jsx](https://www.npmjs.com/package/markdown-to-jsx) override, I ran into the following error.

> `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

I found a hack but it’s dirty. See https://github.com/probablyup/markdown-to-jsx/issues/209#issuecomment-591609187

Would it be bad practice to allow users to choose to wrap `ZOOM` in a `span` vs a `div`? Perhaps a `wrapTag` option that accepts `span` and `div` and defaults to `div`?

Tested `span` on recent versions of Firefox, Safari, Edge and Chrome and everything looks fine.

**Comment by rpearce** [comment]
It's probably better to use a `<span>` for this. I'll see what I can do

**Comment by sunknudsen** [comment]
Thanks @rpearce.

**Comment by rpearce** [comment]
No worries! Thank you. Might be tomorrow before I can get to it.

**Comment by sunknudsen** [comment]
Morning @rpearce. Looking forward to this feature as I can’t easily hack my way around it. If you haven’t started work on it, I could give it a go once the TypeScript [PR](https://github.com/rpearce/react-medium-image-zoom/pull/235) is merged.

**Comment by rpearce** [comment]
Sorry I missed this yesterday. By all means, if you want to contribute a PR, that would be awesome

**Comment by rpearce** [comment]
Okay TS is all merged up and shipped in `4.2.0`
