### ISSUE TITLE
A way to add a caption to the zoomed image?

### ISSUE THREAD

**Issue by n1ghtmare** [rpearce/react-medium-image-zoom#242]
This issue is a: 

- Question / support request

## Description
Is there a way to add a caption when the image is zoomed? I looked in the documentation, but couldn't find anything. Any help would be much appreciated.

**Comment by rpearce** [comment]
You can wrap the `<Zoom>` around anything you want to.

If you look at the `<figure>` example, https://github.com/rpearce/react-medium-image-zoom/blob/master/stories.js#L161-L205, you could instead wrap the `<Zoom>` around the `<figure>`, itself, and get the image and caption to zoom.

**Comment by n1ghtmare** [comment]
Yes, thank you. I need better comprehension skills... or a break. Thanks again, much appreciated!

**Comment by rpearce** [comment]
No worries at all! You are always welcome to ask anything you like

**Comment by rpearce** [comment]
@n1ghtmare Hi! I'm working on adding a feature that includes captioning. Do you have any thoughts on this approach? https://github.com/rpearce/react-medium-image-zoom/issues/332#issuecomment-1207252231

**Comment by rpearce** [comment]
@n1ghtmare Hi! As of `v5.1.x`, you can provide any custom modal content you like, and here is an example: https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--modal-figure-caption
