### ISSUE TITLE
Escape keydown event is not propagating for Controlled component

### ISSUE THREAD

**Issue by rokoroku** [rpearce/react-medium-image-zoom#246]
This issue is a: 
- Bug report

## Expected behavior
- keydown event should be propagated if image is not zoomed, and keydown event for Escape is widely used.

## Actual behavior
- keydown event is always ignored by Controlled component

## Link to repository/example of behavior
https://codesandbox.io/s/long-framework-u14xj?file=/src/App.js
Open console and try "Escape" keypress.

**Comment by rpearce** [comment]
Amazing job on the bug report, example, _and_ pull request! I love it. As I said on the PR, I'll get to merging this up tomorrow.
