### ISSUE TITLE
Zoom status doesn't always update when props.isZoomed changes.

### ISSUE THREAD

**Issue by cbothner** [rpearce/react-medium-image-zoom#26]
I would like to use this as a controlled component, where I can toggle its zoomed state in a central state store. It seems like that's what the `isZoomed` prop is for, however if the image has never been zoomed before, then changing the `isZoomed` prop does nothing. If it has been zoomed before, setting `isZoomed` to true does open the zoomed view and setting `isZoomed` to false does close it, but the portal, then, is not deleted and all mouse input to the rest of the page is intercepted. Additionally, being able to set `onZoom()` and `onUnzoom()` callbacks would be useful.

**Comment by rpearce** [comment]
Sounds reasonable! I am traveling so will have to take a look at this after the holidays. Pull requests welcome, though

**Comment by rpearce** [comment]
@cbothner Checking back in on this. I'm still traveling for the majority of January and _might_ be able to get to it in the next month. How pressing is this for you?

**Comment by cbothner** [comment]
It's important but not urgent. I took a crack at it on my fork (cbothner/react-medium-image-zoom@ 406e7566a9f5eb3f35b1b83cfa554ad2c47ad122) but wasn't able to figure out how the controlled property should trickle down to your `<Zoom />` component. As it stands with my commit, it's all good iff `onZoom` and `onUnzoom` are provided and implemented correctly to change `isZoomed`, but it doesn't behave well without them. Specifically, if `isZoomed` is set in props, the component zooms in; but then `<Zoom />` can be unzoomed on click or scroll, leaving the interface broken. I haven't been able to keep playing with it since before the holidays.

If you could quickly describe an idea for me to implement or wanted to work from where I've gotten, please let me know.

**Comment by rpearce** [comment]
Just spent an hour trying to get something easy going -- I hacked it 90% of the way, but the code really needs to be refactored to be able to handle the states that can exist between its own state management and specified state at any given time.

**Comment by cbothner** [comment]
Just checking in on this.  This morning I learned that installing packages from github using npm is _way harder than it needs to be_ because npm doesn't run build scripts (or even download the src...), so I'm hoping that some of this functionality can make its way into an npm release someday.

**Comment by rpearce** [comment]
Regarding NPM: NPM is a pretty strong tool that does exactly what you tell it to. A prebuild NPM script will run what you tell it to before publishing so that if you install it, you will have a generated file downloads that may not be stored on github (by design). Also, it's not a good idea to require src/ code for front end apps because that code is typically written in future JavaScript that isn't designed for all browsers, so the solution is to rely on the build output code. 

* * *

I've just gotten to New Zealand and set up my new life here.

This issue is one that may require a rewrite to how the package works internally from what I've seen and therefore is one that requires some time and effort. I'll see what I can do over this weekend and keep this thread updated.

**Comment by cbothner** [comment]
Congrats on the big move—don't spend too much time inside at the computer. But big thanks for whatever you can do.

Re: the npm comment, I was referencing [this old issue](https://github.com/npm/npm/issues/3055). Just makes it hard to use tweaked modules in production environments like heroku unless one does store the build artifacts in the source repo (yuck!)

**Comment by rpearce** [comment]
@cbothner can you check [this branch](https://github.com/rpearce/react-medium-image-zoom/tree/zoom-mgmt) out and give it a shot? This branch _should_ fix the bug for not being able to dictate `isZoomed` from the parent component.

Here is a rough guide to how to test locally, if you don't already know how (check [the NPM docs on link](https://docs.npmjs.com/cli/link) out for more info:

1. pull this branch down to your local machine for this project (don't think a fork will do)
1. make sure you check out the branch
1. `$ npm run build:example` to compile all the things
1. `$ npm link`
1. go to your project and remove the `node_modules` folder
1. `$ npm link react-medium-image-zoom`
1. `$ npm i` (or `$ yarn`)
1. at this point you should have the local project installed in your project. So test it out
1. when you're done, from your project: `$ npm unlink react-medium-image-zoom`, remove the `node_modules`, and then reinstall them with the originals
1. from this project, `$ npm unlink`

**Comment by rpearce** [comment]
@cbothner do you have an example repo you're using where I could help you test this bug fix? Might make this fix go out faster

**Comment by cbothner** [comment]
First, _thank you_ for the quick work on this. I had added [a little timed zoom/unzoom widget](https://github.com/cbothner/react-medium-image-zoom/blob/master/example/src/app.js#L6) to the example in my fork, which was what I'm testing with. Testing your branch, it totally works as a controlled component, but I think I'm seeing one bug: when setting `isZoomed = false` from the parent component, it replaces the big image with the small version and never switches it back. [This PR](https://github.com/rpearce/react-medium-image-zoom/pull/27) should fix it.

**Comment by rpearce** [comment]
@cbothner After me being dumb and not merging things correctly, all of this is now published as `0.7.1`. I published this as a patch version because no breaking changes were introduced (major version), no additions were made (minor version) and this is really more of a bug fix.

**Comment by rpearce** [comment]
@cbothner please let me know if there are any issues for you so we can work through them. Unfortunately, automated testing for this would be nice, but also a bit of a pain in the rear.
