### ISSUE TITLE
Should be able to append CSS classes

### ISSUE THREAD

**Issue by rikusen0335** [rpearce/react-medium-image-zoom#264]
This issue is a:
- Feature request

## Description
Currently you can add CSS **styles** with `wrapStyle` prop, but we need to add css through `string` like:

```html
<Zoom className={classes}>
  <img something={something} />
<Zoom>
```

Because there's some cases to use CSS Modules or utility first css frameworks like Tailwind CSS.

**Comment by rpearce** [comment]
@rikusen0335 Thank you for your feature request idea contribution to the project!

There is another major rewrite underway that will change how the component is consumed, and it will allow you to do what you require with styling.

I don't know when version 5 will be available, and I will keep this issue open until it is resolved.

Thanks again.

**Comment by rikusen0335** [comment]
Thank you for answering! I am looking forward to it 🥇

**Comment by rpearce** [comment]
Update on v5 FYI: https://github.com/rpearce/image-zoom/discussions/274

**Comment by rpearce** [comment]
@rikusen0335 I'm working on things and am unsure how I want to go about this. At present, you can override/add on to [the default styles](https://github.com/rpearce/react-medium-image-zoom/blob/main/source/styles.css), but passing a single `className` — now, as well as for the next version — raises some questions.

* What would you be looking to achieve that you couldn't by targeting `.my-class [data-rmiz-wrap] { }` in your CSS?
* Should there be a `className` prop be added to _every_ element, including all of the modal ones? (This feels incorrect to me)

I know it's been a while, and thank you for your time.

* * *

Here's the latest update on the work being actively done! https://github.com/rpearce/react-medium-image-zoom/discussions/274#discussioncomment-2946565

**Comment by rikusen0335** [comment]
You probably need to override classes into every element, like if you making the lib, I mean like:
```jsx
const Zoom = ({ baseClasses, secondClasses, src }) => {
  return (
    <div className={`base ${baseClasses}`}>
      <figure className={`second ${secondClasses}`}>
        <img src={src} />
      </figure>
    </div>
  )
}
```

So, because recent CSS-in-JS stuffs are bit difficult to use css selectors.

**Comment by rpearce** [comment]
That seems like potentially a lot of classes to accept and use; in the `v5-dev` branch code, I would need to accept 9 different class names to cover all the elements.

Don't all the CSS-in-JS provide options to break out of their modules? E.g.,
* https://github.com/css-modules/css-modules#exceptions
* https://emotion.sh/docs/nested 
* https://emotion.sh/docs/globals

Using the example from https://emotion.sh/docs/nested, here's how you would target [`data-rmiz` from the `v5-dev` branch](https://github.com/rpearce/react-medium-image-zoom/blob/954f8f8457d42630b9a4468a2a142c163627390f/source/Base.tsx#L234):

```jsx
const myImgAndText = css`
  color: purple;
  [data-rmiz] { /* some styles here */ }
`
```

Or going with the global approach from emotion:

```jsx
<Global
  styles={css`
    [data-rmiz] { /* some styles here */ }
    [data-rmiz-content] { /* some styles here */ }
  `}
/>
```

**Comment by rpearce** [comment]
Thank you for asking your question and communicating in hopes of making this better! I've added you to the README's all contributors list:

<img width="422" alt="imagen" src="https://user-images.githubusercontent.com/592876/173964424-9cf2ed79-b56e-43b5-9ee0-d727547805b8.png">

**Comment by rikusen0335** [comment]
I even didn't anything xD
But thank you!

**Comment by rpearce** [comment]
You asked a question and thought through some ideas with the hopes of making it better! That is a contribution ❤️
