### ISSUE TITLE
"This site appears to use a scroll-linked positioning effect" issue on Firefox

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/react-medium-image-zoom#265]
This issue is a:

- Bug report

Recently noticed zoom out transition (while scrolling) is choppy on Firefox. I opened console and following messages is present.

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

![bug](https://user-images.githubusercontent.com/2117655/105481355-d569c900-5c9e-11eb-81d2-056f5eba8c85.gif)

## Expected behavior

Fluid transition with no console warning

## Actual behavior

Choppy transition with console warning

## Steps to reproduce behavior

Issue is present live at https://sunknudsen.com/privacy-guides/how-to-make-sure-app-is-not-running-in-the-background-on-macos.

Let me know if I can help further debug this issue. My gut feeling is it should be reproducible using any use case of `image-zoom/issues/new` on Firefox 84.0.2 (64-bit).

**Comment by rpearce** [comment]
@sunknudsen Yes – great report! I am aware of the scrolling imperfection and am working on all this in the `rewrite` branch that is probably 30% done. There are a LOT of things to consider.

**Comment by sunknudsen** [comment]
Hey @rpearce,

I recently implemented [modern-normalize](https://www.npmjs.com/package/modern-normalize) and noticed the scrolling performance glitch on Firefox was significantly less present although the following warning still appeared in the console.

> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

The following CSS is what is responsible for the "fix".

```css
:-moz-focusring {
  outline: 1px dotted ButtonText;
}
```

**Comment by rpearce** [comment]
@sunknudsen It looks like code you're referencing is there to

> Restore the focus styles unset by the previous rule.

So the moz-focus-inner gets unset and then gets reset by this rule... It might be early, but I'm not quite understanding how setting the outline to 1px dotted fixes the issue...

Relatedly, I don't think I would want an image zooming library to determine the focus styles of a site?

**Comment by sunknudsen** [comment]
> Relatedly, I don't think I would want an image zooming library to determine the focus styles of a site?

I agree... I was naively suggesting that this CSS could perhaps be set only in the context of `react-medium-image-zoom`.

Before considering a PR, I wanted to share my findings... I believe adding this "hack" to the docs (if it isn't implemented in code) could benefit others.

**Comment by rpearce** [comment]
If the issue remains when I get this darn thing done, I'll do that. Thanks for finding this and reporting back

**Comment by rpearce** [comment]
Update on v5 FYI: https://github.com/rpearce/image-zoom/discussions/274

**Comment by rpearce** [comment]
Should be closed now with the release of `5.0.0`. Let me know if you see this again!
