### ISSUE TITLE
Combination of next/image with layout responsive

### ISSUE THREAD

**Issue by xmflsct** [rpearce/react-medium-image-zoom#281]
This issue is a: 

- Question / support request

## Description
Using `next/image` so far so great. But when using `layout='responsive'`, the image's width and height are somehow set to `0`. Is there any way around? https://nextjs.org/docs/api-reference/next/image#layout

**Comment by rpearce** [comment]
Hi, @xmflsct, and thank you for bringing this to my attention.

Do you have a demo that you could share that reproduces the issue? I've never used nextjs before, so I don't know the answer off the top of my head.

I'll also leave this open in case somebody else knows.

**Comment by xmflsct** [comment]
Thank you very much for your time @rpearce !

See demo here https://mre-next-image-zoom.vercel.app/
And the code at https://github.com/xmflsct/mre-next-image-zoom/blob/main/pages/index.js#L33L66

The top left is with `image-zoom` and `responsive` in `next/image`.
The top right is without `image-zoom` and `responsive in `next/image`.
The bottom left is with `image-zoom` and without `responsive` in `next/image`.

More about `next/image`'s layout option at https://nextjs.org/docs/api-reference/next/image#layout

**Comment by rpearce** [comment]
Thank you! I'll take a look at this when I get some time in the next few days.

**Comment by rpearce** [comment]
Haven't had time to look at this yet but it's on my mind. I appreciate your patience.

**Comment by xmflsct** [comment]
@rpearce No worries at all!

**Comment by rpearce** [comment]
Ah... good news and bad news.

Good news: I know what the problem is.
Bad news: There might not be a way around this.

The issue is that the `img` has `position: absolute` on it, and the RMIZ wrapper is using `display: inline-flex` to do something fancy (this needs to change); the browser can't determine how big the image is because of the `position: absolute` and `width: 0; height: 0;` on your image.

I'm going to consider patching `v4` to fix some of these outstanding issues so that people aren't continually blocked by my personal life with regard to re-implementing `v5` (https://github.com/rpearce/image-zoom/discussions/274).

I'll prioritize this one because it is the same root cause of a few other issues, namely https://github.com/rpearce/image-zoom/issues/259.

**Comment by rpearce** [comment]
This is weighing on my mind; I'll get it done. There is very little time with an infant

**Comment by xmflsct** [comment]
@rpearce Hope all is well. Following up with this issue. :)

**Comment by zacherygentry** [comment]
+1 for running into this same issue

**Comment by rpearce** [comment]
Thanks for checking back in. I'll think about it some more this week; it's going to involve some hefty changes.

**Comment by rpearce** [comment]
@xmflsct Removing that has other ramifications that I need to account for.

**Comment by rpearce** [comment]
Update: I'm working on this and some other updates a little bit each night. They are all tied together

**Comment by btoro** [comment]
Any updates on this?

**Comment by rpearce** [comment]
@btoro The issue laid out here has a solution, but it requires a lot of changes, and so it makes sense to do all the changes together. I made a ton of progress my last time trying to make changes here that resolved the issue in a branch, but I burned out on some of the math for zooming background images, and it's in a hacked-together state. I'm going to get it done, and it's just a matter of finding the time with having a toddler.

**Comment by btoro** [comment]
Understood! Thanks for the update. I managed to come up with a temporary solution that I'll share to help others. There are likely cases where this doesn't work properly, but it met my needs:

```
      <Zoom
        wrapStyle={{ minWidth: "100%" }}
      >
        <div className=" min-w-full relative"> // CSS-> minWidth:100%, position: relative;
          <Image  layout="responsive" {...props} />
        </div>
      </Zoom>
```

**Comment by rpearce** [comment]
If anyeone finds some spare time and wants to give the latest build a whirl to try this out:

```sh
npm i --save react-medium-image-zoom@5.0.0-beta2.6
```

And, if you aren't already,

```jsx
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

// ... your other code

<Zoom>
  <MyImage />
</Zoom>
```

The updated [`v5-dev` README is here](https://github.com/rpearce/react-medium-image-zoom/tree/v5-dev#react-medium-image-zoom), and there are some breaking changes to the extra options passed to be aware of, if you're using the options.

Thanks for your time!

**Comment by rpearce** [comment]
Should be closed now with the release of `5.0.0`

**Comment by daniszaidan** [comment]
@rpearce 
in v4, i'm using wrapStyle to solved next/image problem.
and in v5 wrapStyle  removed, how to solve this now?

`<Zoom
                        wrapStyle={{
                          width: '100%',
                          height: '100%',
                        }}
                      >
                        <Image
                          src="blabla"
                          layout="fill"
                          objectFit="cover"
                        />
                      </Zoom>`

**Comment by rpearce** [comment]
@daniszaidan Are you saying this is a problem in v5? If so, that would merit re-opening the issue, as I may have missed it.

**Comment by daniszaidan** [comment]
@rpearce yeah i think this is a problem in my case, because i need to write inline style at parent next/image (<Zoom/>)

**Comment by rpearce** [comment]
@daniszaidan If you're able to provide some steps for me to easily reproduce this with v5, I'll be able to investigate it much faster. An example repo, some specific steps here, or something else! 🙇
