### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by sunknudsen** [rpearce/react-medium-image-zoom#322]
Hey Robert,

Great to see you are working on the project again.

Updated deps of one of my projects with target minor (no breaking changes) and noticed that [react-medium-image-zoom](https://github.com/rpearce/react-medium-image-zoom) has become an ESM module (see [commit](https://github.com/rpearce/react-medium-image-zoom/commit/ea5514691f77f35d59f77f7719047fb0cfcc8e21)).

This breaking change broke my app witch (sadly) is not ESM-ready… I am wondering how to best handle this… most projects I encounter mention switch to ESM on [releases](https://github.com/rpearce/react-medium-image-zoom/releases) page and increment semver using [major](https://semver.org/) version so bug fixes can still be pushed to non-ESM deployments.

> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/sunknudsen/Code/sunknudsen/react-optimized-image/node_modules/react-medium-image-zoom/dist/cjs/index.js from /Users/sunknudsen/Code/sunknudsen/react-optimized-image/lib/OptimizedImage.js not supported.

Btw, I know I should migrate my projects to ESM but I am using a stack that is very hard to migrate.

Have a wonderful day,

Sun

**Comment by sunknudsen** [comment]
This issue is apparently very hard to work around given `^` dependency model… is there a way ESM change can be reverted in `v4.4.3` and moved to a `v5.0.0` release?

**Comment by rpearce** [comment]
@sunknudsen 🤦‍♂️ I'm so sorry I made trouble for you. Yes, that is what should happen, but I can't do it until tonight.

I'm getting all of the app in working order in `main` so I can incrementally improve the actual component code, and this is one of those bumps along the way.

**Comment by rpearce** [comment]
@sunknudsen Am I going to need to keep supporting commonjs for you? I don't want to let you down, and it's not _that_ big of a deal

**Comment by sunknudsen** [comment]
Hey @rpearce,

Thanks for taking the time to follow-up.

> 🤦‍♂️ I'm so sorry I made trouble for you.

No worries, maintaining a project like this is so much work… I am so sorry I had to raise flag.

> Yes, that is what should happen, but I can't do it until tonight.

That would be awesome, but only if you have evening bandwidth available. 🤗

> I'm getting all of the app in working order in main so I can incrementally improve the actual component code, and this is one of those bumps along the way.

Feel you… blessed you are still maintaining project.

> Am I going to need to keep supporting commonjs for you?

That would be **amazing**, but keeping v4 CommonJS and patching security issues (if any) would likely be enough.

There is a lot of push towards ESM so one can expect feature releases to be ESM-only (at the very least, this is what I am seeing around).

**Comment by rpearce** [comment]
Okay, I will keep this as commonjs for v4 (which makes sense... changing that was definitely a breaking one).

Thanks for your patience.

**Comment by rpearce** [comment]
@sunknudsen This _should_ be fixed in `v4.4.3`. Please let me know if it is not fixed.

**Comment by sunknudsen** [comment]
@rpearce Looking good, thanks for the fix. 🙌

**Comment by rpearce** [comment]
I put a question out in the twitterverse about this: https://twitter.com/RobertWPearce/status/1530970576042565632
