### ISSUE TITLE
it cannot be used for more than one image!

### ISSUE THREAD

**Issue by arviinmo** [rpearce/react-medium-image-zoom#331]
- Bug report
- Question / support request

Hi dear maintainers.
Recently I've installed this package and tried to add  this awesome feature to my blog. Although this is a great project and I really appreciate your hard work for building this amazing project, I think there is a bug in the package.
When I tried this package for my blog I saw that the only first image worked correctly and in other images I couldn't zoom-in and out.
please check this issue and if it's possible fix the bug.

**Comment by arviinmo** [comment]
and this is [my blog](https://arvin.vercel.app/blog)
@rpearce @dougg0k @sunknudsen @spencerfdavis

**Comment by PaoloDiBello** [comment]
> and this is [my blog](https://arvin.vercel.app/blog) @rpearce @dougg0k @sunknudsen @spencerfdavis

Are you using ControlledZoom? If that's the case what I did was setting a specific state based on the id of the image clicked and based on that I had a condition in isZoomed to see if it was the image that was clicked. 

So I did something like this 
`isZoomed={zoomedImageId === image.id}`

If you are using UnControlledZoom maybe for some reason it is not understanding what image to pick among the other images, as for me ControlledZoom works fine

**Comment by rpearce** [comment]
Hi, and thanks for asking your question!

This project has never purposefully supported zooming more than 1 image inside of a `<Zoom>` component.

Instead, each instance of an image should be wrapped in a `<Zoom>` component.

Please let me know if you have more questions around this!

**Comment by arviinmo** [comment]
> > and this is [my blog](https://arvin.vercel.app/blog) @rpearce @dougg0k @sunknudsen @spencerfdavis
> 
> Are you using ControlledZoom? If that's the case what I did was setting a specific state based on the id of the image clicked and based on that I had a condition in isZoomed to see if it was the image that was clicked.
> 
> So I did something like this `isZoomed={zoomedImageId === image.id}`
> 
> If you are using UnControlledZoom maybe for some reason it is not understanding what image to pick among the other images, as for me ControlledZoom works fine

thanks for your response.
for now i'm just using <Zoom> component

**Comment by arviinmo** [comment]
> Hi, and thanks for asking your question!
> 
> @arviinmo @PaoloDiBello This project has never purposefully supported zooming more than 1 image inside of a `<Zoom>` component.
> 
> Instead, each instance of an image should be wrapped in a `<Zoom>` component.
> 
> Please let me know if you have more questions around this!

but it would be great if it could handle situations like this.

**Comment by rpearce** [comment]
@arviinmo I have looked at doing this before, but it always left me  having to mutate the user's DOM values manually more than I was comfortable with. Recursively iterating through `this.props.children` is also difficult to get right.

I will keep this in mind for the future in case I think of a good way to support this (maybe a component called `<ZoomAll>`), but that is not something I'm going to commit to.

Thank you for your thoughts!

**Comment by arviinmo** [comment]
> @arviinmo I have looked at doing this before, but it always left me having to mutate the user's DOM values manually more than I was comfortable with. Recursively iterating through `this.props.children` is also difficult to get right.
> 
> I will keep this in mind for the future in case I think of a good way to support this (maybe a component called `<ZoomAll>`), but that is not something I'm going to commit to.
> 
> Thank you for your thoughts!

thanks for your response again,
that would be great!
please notify me if you added the feature.

cheers,
Arvin
