### ISSUE TITLE
Preload zoomImage url

### ISSUE THREAD

**Issue by ismay** [rpearce/react-medium-image-zoom#35]
Do you think preloading the zoomImages is a useful addition to this component? It seems quite useful to have the component automatically add

```
<link rel="preload" href="a_zoomImage.jpg" as="image">
```

for each zoomImage. Interested in what you think and whether or not that would be a useful optimisation. As I see it it should allow the browser to decide for itself whether or not to download the images ahead of time, and should mean that the zoomImages are available earlier.

**Comment by rpearce** [comment]
@ismay I do think that preloading of some sort would indeed be useful if specified by the developer.

What are you thoughts on what this would look like with regards to this API?

**Comment by ismay** [comment]
> What are you thoughts on what this would look like with regards to this API?

I'd say a `shouldPreload` boolean, set to `false` by default. When set to `true`, it appends a preload link with the zoomImage url to the `<head>` if there is a `zoomImage`. That'll make sure that browsers start downloading the zoomImages as soon as possible, instead of waiting until the user zooms.

**Comment by rpearce** [comment]
@ismay I'll take a look at it when I get some free time in a couple of days. Thanks for your ideas

**Comment by rpearce** [comment]
@ismay take at a look at https://github.com/rpearce/react-medium-image-zoom/pull/36 and see if this solution/explanation makes sense or not.

**Comment by rpearce** [comment]
@ismay I'm taking a look at another issue, and I keep getting the feeling that this preload functionality should not actually be a part of this library and should live in the client's application code. What would prevent you in your app from doing
```js
<span>
  <link rel="preload" href={...} as="image" />
  <ImageZoom ... />
</span>
```
which is what the component is currently doing for you?

**Comment by ismay** [comment]
Yeah after having used it for a while I think you're right. No reason this can't be added by the user with a wrapper.

**Comment by ismay** [comment]
Might be good to remove it with the release of v2

**Comment by rpearce** [comment]
@ismay thanks for the feedback. I'll pull the v2 commit _out_ of that open PR, create a new one, and then the v2 release will come after all that is set
