### ISSUE TITLE
Received NaN for the `width` attribute. If this is expected, cast the value to a string.

### ISSUE THREAD

**Issue by AntoineS92** [rpearce/react-medium-image-zoom#357]
## Issue Type

- [ ] Bug report
- [ ] Feature request
- [X] Question / support request
- [ ] Other

## Description

Hi, I am trying to use the libraby. Everything is working fine but I have this warning in the console. 
I made some tests, and it appears that it is because of react-medium-zoom as I don't have the warning if I don't use it. 

I was hoping maybe you could help. I do not know if this is a bug or if there is something I am not doing good.

Thank you very much !

**Comment by AntoineS92** [comment]
<section className={styles.imageList}>
            {nosReferencesImagesData.images
              .filter((image) => image.category.includes(clickedCategory))
              .slice(0, numberOfImagesDisplayed)
              .map((image, index) => {
                return (
                  <div
                    className={styles.imageList__SingleImageContainer}
                    key={index}
                  >
                    <Zoom>
                      <img
                        src={image.imgSrc}
                        alt={nosReferencesImagesData.alt[image.category[1]]}
                        className={styles.imageDesktop}
                        width="600"
                        height="400"
                      />
                    </Zoom>

                    <Zoom>
                      <img
                        src={image.imgSrcMobile}
                        alt={nosReferencesImagesData.alt[image.category[1]]}
                        className={styles.imageMobile}
                        width="313"
                        height="208"
                      />
                    </Zoom>

                    {/* all pictures have the same width & height values */}
                  </div>
                )
              })}

            <div className={styles.imageList__SingleImageContainer}>
              <div className={styles.emptyImageDivForFlexWrap} />
            </div>
          </section>

**Comment by AntoineS92** [comment]
@rpearce I have the problem with any image in my list of images. 
I also tried with a random image from the internet and I have the same issue

**Comment by rpearce** [comment]
Thanks for the quick response! I won't be able to debug this until later, but I can communicate.

Is your mobile image `display: none` by chance?

**Comment by AntoineS92** [comment]
Thank you very much for your help ! Sorry for the inconvenience

**Comment by rpearce** [comment]
Do you think the library should be checking the `display` value of the image element it finds?

**Comment by AntoineS92** [comment]
I guess that could be useful. I'm quite junior so I wouldn't have a strong opinion about it

**Comment by rpearce** [comment]
Your input is still important! Thank you for it.

I will leave this issue open while I think about it some more.

**Comment by trebua** [comment]
I would also appreciate if the library would check and handle display value of image elements. We are using your lib in combination with an image carousel (https://www.npmjs.com/package/keen-slider), and we get the same warning.

**Comment by mmxdr** [comment]
I have this warning too and i use display property for hiding mobile or desktop image.

**Comment by rpearce** [comment]
Ok! This is something I will work on fixing as soon as possible. Thanks for the reports, folx.

**Comment by rpearce** [comment]
I'm working on this, and it should be in the next `v5.1.0` beta version. If that checks out, I'll see about doing an official `5.1.0` release.

**Comment by rpearce** [comment]
This PR should fix the issue, https://github.com/rpearce/react-medium-image-zoom/pull/365, and this extra commit, https://github.com/rpearce/react-medium-image-zoom/commit/c36e04bdfa66705c0a7bfbcf9c05d549262f56c9, should ensure that `NaN` never makes its way to `width` and `height` props. 

It's been merged into the `v5-dev` branch and beta released as `react-medium-image-zoom@5.1.0-beta.9`. Please try that version out and let me know if you have any issues.

**Comment by rpearce** [comment]
@AntoineS92 @trebua @mmxdr This has been released in `v5.1.0`!

I added you to the All Contributors section in the README for your contributions. Thank you for your time 💜

**Comment by AntoineS92** [comment]
Thank you ! I will try it as soon as I have time ! 
You rock

**Comment by mmxdr** [comment]
@rpearce perfect, works now!
thank you for your work and time!
