### ISSUE TITLE
Facing some strange issue with additional loader

### ISSUE THREAD

**Issue by sumitaney** [rpearce/react-medium-image-zoom#360]
[##](url) Issue Type
<img width="1440" alt="Screen Shot 2022-09-23 at 11 43 49 PM" src="https://user-images.githubusercontent.com/49674966/192084059-f29b21d4-b06a-46c2-aa4a-3b695034630c.png">

- [ ] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description

Place detailed information here

./node_modules/react-medium-image-zoom/dist/index.js 29:45
Module parse failed: Unexpected token (29:45)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| }
| 
> const testElType = (type, el) => type === el?.tagName?.toUpperCase?.();
| 
| const testDiv = el => testElType('DIV', el) || testElType('SPAN', el);

**Comment by rpearce** [comment]
Hi, and thanks for asking your question!

I'm not sure how recent your dependencies are, but [optional chaining has great support](https://caniuse.com/mdn-javascript_operators_optional_chaining) and should have full support as of nodejs@14.0 (LTS is nodejs@16.7.1 and current is nodejs@18.9.1).

If you need a babel plugin for this, I think this might be the one:
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

Given this is intended build output and is documented in the readme (see below), I'm going to close this as an issue, but please follow up with another questiion if you need more help.

> This library's compilation target is ES2022, but it only uses features from ES2020 and below. If you find you need to support older environments, run this project through your build system.

— https://github.com/rpearce/react-medium-image-zoom#quickstart
