### ISSUE TITLE
Image is hidden when pressing escape during hiding animation

### ISSUE THREAD

**Issue by SanderHeling** [rpearce/react-medium-image-zoom#378]
## Issue Type

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description

When you close the modal by clicking on it and then press escape while it's animating it will hide the modal and keep `visibility: hidden;` on the content. This issue can be easily recreated in the "[Custom Modal Styles](https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--custom-modal-styles)" story.

Tested in Chrome Version 106.0.5249.119
![ezgif-5-598d4c69b8](https://user-images.githubusercontent.com/1461215/197753276-c0210f5f-c599-444b-8805-4bc1785c361b.gif)

**Comment by rpearce** [comment]
@SanderHeling This should now be resolved as of `v5.1.2`, and the example you linked to above should now be functioning properly.

Thanks for your bug-report contribution! You've been added to the all-contributors list in the README!
