### ISSUE TITLE
Import PropTypes from separate package

### ISSUE THREAD

**Issue by ismay** [rpearce/react-medium-image-zoom#38]
React 15.5 has deprecated importing `PropTypes` from the `react` package. Instead they're now recommending to use the new `prop-types` package. Any packages that use the old import strategy will produce a console error.

* See here: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
* Only this line has to be updated: https://github.com/rpearce/react-medium-image-zoom/blob/3a9f30d0d1bae2140f30c915782deedd20a41229/src/react-medium-image-zoom.js#L1

**Comment by rpearce** [comment]
Thanks! It's been on my to-do list. Feel free to open a PR if you find the time.

**Comment by ismay** [comment]
Submitted a fix in #39
