### ISSUE TITLE
Pass in caption text to the CustomZoomContent

### ISSUE THREAD

**Issue by jeremyzilar** [rpearce/react-medium-image-zoom#381]
## Issue Type

- [ ] Bug report
- [x] Feature request
- [ ] Question / support request
- [ ] Other

## Description

Thank you for your work on adding in the ability to customize the zoom modal's content 🎉 ([link](https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--modal-figure-caption))

However, using the exact example in the repo, I am having the hardest time trying to pass in the caption text to the `CustomZoomContent` component. What is the best way to pass in dynamic text that will appear in the Zoomed state?
https://github.com/rpearce/react-medium-image-zoom/blob/main/stories/Img.stories.tsx#L248

**Comment by rpearce** [comment]
Hi, @jeremyzilar! Let's see if we can get you sorted.

The `CustomZoomContent` in this example,

https://github.com/rpearce/react-medium-image-zoom/blob/16ebc24d38c28739f39c99b1f6bb616f7b0adb93/stories/Img.stories.tsx#L236

can be anything. If you need to do this dynamically, I suggest the following approach:

```js
```

**Comment by rpearce** [comment]
I also want to say _thank you_ for your time and whatever you contributed while with 18F, digital.gov, the U.S. Web Design System, and the rest.

**Comment by rpearce** [comment]
It doesn't seem there's an outstanding issue here, so I'm going to close this. Please feel free to ask more questions!

**Comment by jeremyzilar** [comment]
So in trying both your example above, and the exact example in your storybook, the place where I keep getting hung up is that the modal doesn't close.

It seems that this `open` attribute is not getting removed or unset when closing the modal, where it is getting unset in your [DEMO](https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--modal-figure-caption).
```
<dialog aria-labelledby="rmiz-modal-img-53e673c3d335" aria-modal="true" data-rmiz-modal="" id="rmiz-modal-53e673c3d335" role="dialog" open>
```

https://user-images.githubusercontent.com/395641/205322143-89d10b7f-dbc7-4bb2-8332-15ae02873bbe.mov

I couldn't find the spot in your repo where you are setting and unsetting `open`, but will keep digging around.

Here are the components I have:

```
const ContextImage = (props: any) => {
  return (
    <Zoom
      {...props}
      zoomImg={{
        alt: `thing`,
        src: props.url,
        srcSet: props.url,
      }}
      ZoomContent={ContextImageZoomed}
    >
      <Image key={props.id} src={props.url} alt={``} objectFit="scale-down" width={200} height={200} />
    </Zoom>
  )
}

const ContextImageZoomed = (props: any) => {
  const { buttonUnzoom, img, modalState } = props

  const [isLoaded, setIsLoaded] = useState(false)

  const imgProps = (img as ReactElement<HTMLImageElement>)?.props
  const imgWidth = imgProps?.width
  const imgHeight = imgProps?.height

  const classCaption = useMemo(() => {
    const hasWidthHeight = imgWidth && imgHeight
    const imgRatioLargerThanWindow = imgWidth / imgHeight > window.innerWidth / window.innerHeight

    return cx({
      "zoom-caption": true,
      "zoom-caption--loaded": isLoaded,
      "zoom-caption--bottom": hasWidthHeight && imgRatioLargerThanWindow,
      "zoom-caption--left": hasWidthHeight && !imgRatioLargerThanWindow,
    })
  }, [imgWidth, imgHeight, isLoaded])

  useLayoutEffect(() => {
    console.log("modalState ---->", modalState)
    if (modalState === "LOADED") {
      setIsLoaded(true)
    } else if (modalState === "UNLOADING") {
      setIsLoaded(false)
    }
  }, [modalState])

  return (
    <>
      {buttonUnzoom}
      <div className={classCaption}>
        <Image src={img.props.src} alt={``} objectFit="scale-down" width={img.props.width} height={img.props.height} />
      </div>
    </>
  )
}
```

**Comment by jeremyzilar** [comment]
Oh I see! You are passing in the image component `{img}`!!  
I was making another `<Image..` and that is where it was going south. 
Mine should be 
```
return (
    <>
      {buttonUnzoom}
      <div className={classCaption}>
        {img}
        <p>possible caption here</p>
      </div>
    </>
  )
```

**Comment by rpearce** [comment]
So are you all sorted?

On the attribute topic, the `open` attribute gets set by the browser when `showModal()` is called on a `<dialog>` element.
