### ISSUE TITLE
[bug] every image is being downloaded 3 times

### ISSUE THREAD

**Issue by GorvGoyl** [rpearce/react-medium-image-zoom#383]
Inspecting dev tools shows that the image is downloaded three times when using this library. 

You can check it from the storybook example too:
https://rpearce.github.io/react-medium-image-zoom/?path=/story/img--regular
![screenshot 2022-11-24 at 14 26 20@2x](https://user-images.githubusercontent.com/7106086/203737308-df1df111-7ece-4eb5-9047-044caa2c5941.png)

**Comment by rpearce** [comment]
Hi! Thanks for asking your question and pointing this out.

It looks like you have "disable cache" enabled, so it will definitely be downloaded >1 time.

The library asynchronously tries to wait for the image to load, and it renders it in a portal once it does. If you've disabled the cache, it'll miss the local browser cache and try to re-fetch.

Please let me know if this is not the case.

**Comment by GorvGoyl** [comment]
thanks that make sense. closing the issue.
