### ISSUE TITLE
dialog tag is not supported in safari < 15.4

### ISSUE THREAD

**Issue by panddr** [rpearce/react-medium-image-zoom#387]
## Issue Type

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description

Dialog tag is supported in safari > 15.3
https://caniuse.com/dialog

**Comment by rpearce** [comment]
@panddr The `<dialog>` element, in the latest browsers, provides functionality by default that would be an awful pain to implement in this library. All of the modal-related things like hiding all content outside the modal, for example, are a pain.

This is the first report I've had with this concern, and I'm not sure that it's something I'm going to put time towards, but I'll keep it open for a little while and see how I feel about it.

**Comment by rpearce** [comment]
@panddr There is too much involved for me to recreate the `<dialog>` element and all of its accessibility from scratch, so I'm going to close this issue.

I don't know if polyfillying `dialog` would work, but here's a start: https://github.com/GoogleChrome/dialog-polyfill
