### ISSUE TITLE
`Esc` to exit zoom doesn't work on Safari

### ISSUE THREAD

**Issue by steven-tey** [rpearce/react-medium-image-zoom#430]
`Esc` to exit zoom works on Chrome, but not Safari:

https://github.com/rpearce/react-medium-image-zoom/assets/28986134/4507dde8-5e18-4bef-af9d-b7011ac18208

**Comment by rpearce** [comment]
It works on Firefox, too, but I've confirmed it doesn't work on Safari. That is so interesting! I'll look into it ASAP.

Thanks for the report.

**Comment by rpearce** [comment]
Investigation: it looks like focus works fine in development (focus is on the close button), but it's being lost to the `<body>` in the built output. I'll update this comment with more discoveries (it may have to wait until later because of parenting duties).

**Comment by steven-tey** [comment]
I tried to repro that in Safari but couldn't get `Esc` to work 😅 

Recording: https://share.cleanshot.com/f26RRMYG

Btw absolutely no rush on this! :)

**Comment by rpearce** [comment]
@steven-tey If you get some time, could you please try this out?

Release candidate bug fix: `react-medium-image-zoom@5.1.7-rc.0`
PR (with instructions for testing using this project, instead): https://github.com/rpearce/react-medium-image-zoom/pull/431

**Comment by steven-tey** [comment]
Oh hey that fixes it!! Esc to unzoom works on Safari with this version! 🤩

https://github.com/rpearce/react-medium-image-zoom/assets/28986134/e9d311c5-e006-4918-8106-95966c64e9da

**Comment by steven-tey** [comment]
Appreciate it, Robert – thanks a lot for the quick fix here! 🙏

**Comment by rpearce** [comment]
This should now be resolved in `react-medium-image-zoom@5.1.7`.

Thanks again for the report, and let me know if you run into any further issues!

**Comment by steven-tey** [comment]
Incredible! Thank you so much again Robert!!
