### ISSUE TITLE
Cannot zoom in docusaurus production build

### ISSUE THREAD

**Issue by levino** [rpearce/react-medium-image-zoom#440]
## Issue Type
Bug report

## Description

I cannot zoom in production, local dev build works fine. I am using docusaurus. Neither local production build, nor nextjs or vercel works. Please see this [PR](https://github.com/levino/levinkeller.de/pull/20) and a [deployment](https://levinkeller-de-git-feature-garden-update-levino.vercel.app/blog/2023/08/23/garden-update) without working zoom from the PR.

**Comment by levino** [comment]
Looks like a problem with [`@docusaurus/plugin-ideal-image`](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image). It creates some intermediary divs, I fear / replaces dom nodes after render.

**Comment by rpearce** [comment]
Hi! I'm sorry you're having trouble with this.

I'm not sure when I can look at your issue at the moment, but hopefully soon.

If you figure it out, PRs are welcome!

**Comment by rpearce** [comment]
@levino Do you want to keep this issue open? I'm not sure I can invest in a different, potentially problematic plugin. Did you find an alternative?
