### ISSUE TITLE
Doesn't work with next/image small images

### ISSUE THREAD

**Issue by tszhong0411** [rpearce/react-medium-image-zoom#444]
## Issue Type

- [x] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

## Description
RMIZ doesn't work with small images. Here is a 640x427 image; when I zoom in, it is so small.
But it has no problem in version 4.3.3.

If I have misunderstood something, please tell me.

Minimal reproduction:

[Stackblitz - RMIZ - Small image](https://stackblitz.com/edit/stackblitz-starters-4vg1m3?file=pages%2Findex.js)

Thanks!

**Comment by rpearce** [comment]
Hi, and thanks for using this and opening an issue.

I believe the answer to your question can be found in this comment: https://github.com/rpearce/react-medium-image-zoom/issues/437#issuecomment-1673184481

In short, your image may be small, and this library won't zoom an image beyond its maximum `naturalWidth` and `naturalHeight`.

If you look at the API in the README, you can pass a `zoomImg` that is a larger resolution image to be used when zooming; that was the solution for the Next.js team in the issue linked above.

* * *

Please let me know how it goes!

**Comment by tszhong0411** [comment]
@rpearce Thanks for your reply. Passing the `zoomImg={{ src }}` with a url of unoptimized image can solve the problem. Or I can make a bigger image.

Really appreciate your help!

**Comment by alagunoff** [comment]
For me that didn't solve the issue since I used `sizes` attribute on the Image component from next.js where I had `srcset` attribute set and even though we set new src for the opened image we still have the same image being opened since we have `sizes` prop set on the Image. I additionally added `srcSet` key with an empty string as a value to `zoomImg` prop
