### ISSUE TITLE
Extra wrapper divs breaks design

### ISSUE THREAD

**Issue by michelson** [rpearce/react-medium-image-zoom#447]
## Issue Type

- [x] Bug report

## Description

New versions of this library wrap the image with extra divs. This breaks some designs.

### Example Without wrapping divs:

This is a video without the wrapper; note that the aspect ratio of the image is kept.

https://github.com/rpearce/react-medium-image-zoom/assets/11976/447fe9fc-9620-4519-9481-bdb588458c23

### Example with library applied:

https://github.com/rpearce/react-medium-image-zoom/assets/11976/a26958c7-5ddc-4924-a3f5-0ad1d5057ac6

Also, images are shrunk when zoomed.

Is there some way to avoid the div wrappers? By the way, I've used this library on version 3.1.2, and it didn't add the extra divs.

**This example demonstrates how the wrapper div breaks the style in our case**

https://github.com/rpearce/react-medium-image-zoom/assets/11976/74f98777-2567-4c0e-a285-9cc52d501aa6

any hints will be greatly appreciated

**Comment by rpearce** [comment]
Hi, and thanks for asking your question! I'm sorry you had trouble.

When it comes to the `<div>`s, they are required for design and accessibility purposes: I needed somewhere to put the button that allows this to be keyboard and screen-reader accessible.

Is this a public project you could share with me, or could you put together a public example I could clone and see if I can give you a solution?

We'll get you sorted, and I apologize for the wait.

**Comment by rpearce** [comment]
Given there's nothing to change on this side, I'm going to close the issue, but we should still use this issue to try to resolve your problem.
