### ISSUE TITLE
Opacity not respected by defaultStyles > overlay value 

### ISSUE THREAD

**Issue by wtfdaemon** [rpearce/react-medium-image-zoom#45]
Can see where (line 610) you are using a bitwise and; to convert the opacity value to 0 or 1 based on visibility.  Unfortunately, this has the side effect of overriding the opacity value I'm trying to pass in this.props.defaultStyles.overlay.  It's important to me, from a design perspective to be able to have a partially opaque background while image is zoomed.

**Comment by rpearce** [comment]
@wtfdaemon do you mind sharing what your props are that you're passing so I can confirm and see about fixing? Thanks for your report!

**Comment by rpearce** [comment]
@wtfdaemon this should be fixed in version `1.0.3`. The PR is linked above this comment if you'd like to take a look at it.

Let me know if you have any more problems, and thanks for raising the issue!

**Comment by wtfdaemon** [comment]
Great work, thanks!
