### ISSUE TITLE
How can remove the border of the button that close the zoom

### ISSUE THREAD

**Issue by TonyFTannous** [rpearce/react-medium-image-zoom#467]
Please i need a help. i can't remove the border of the close button when focus or active it

 .dialog-zoom button:focus,   .dialog-zoom button:active{
    border: none !important
  }

doesn't work

**Comment by rpearce** [comment]
@TonyFTannous Thanks for using this project, and I'm sorry you're having trouble.

If you're referring to the [`outline`](https://developer.mozilla.org/en-US/docs/Web/CSS/outline), that's something that is different across browsers, and unless you replace it yourself with something like `border`, [removing `outline` from focusable elements can create severe accessibility issues](https://www.a11yproject.com/posts/never-remove-css-outlines/).

One thing I don't understand is the CSS class names you're using above, for those are not used in this project. If you would like to style the component differently, you can find all the styles in this file, and [here is the specific selector for overriding the styles for the unzoom button](https://github.com/rpearce/react-medium-image-zoom/blob/1b813cc635a67d2547f2efdc6479080233dba013/source/styles.css#L40).

When it comes to styling this, you can either:

* import the CSS file from the project, like it says it in the README, and then provide your own overrides for those styles
* copy and paste the styles into your own project, modify those, and import your own CSS file without using the one from the NPM module

* * *

I hope that answered your request and provided enough info. This isn't an issue for the project, so I'm closing this, but feel free to keep asking questions here.
