### ISSUE TITLE
PropTypes warning remains

### ISSUE THREAD

**Issue by kendagriff** [rpearce/react-medium-image-zoom#47]
I realize this was probably fixed in #38, but the problem persisted for me:

```
Warning: Failed propType: Invariant Violation: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types Check the render method of `ZoomPortrait`.
```

That's even after updating to React 15.6.1. The only way I could remove it was by removing all references to PropTypes altogether from the library: https://github.com/banzai-inc/react-medium-image-zoom/tree/without-prop-types

Any suggestions?

**Comment by rpearce** [comment]
@kendagriff Thanks for reporting a potential issue. Does this referencing a specific line in the package (number or method name?), or is there a simple way to reproduce this with the example code in the repo? Thank you for your help.

**Comment by rpearce** [comment]
@kendagriff I apologize for not being clearer. I see you reference `ZoomPortrait`, but I assume that is a component in your project. Can you narrow down to where in this project this comes from, or can you recreate somewhere so that I can interact with it and see the problem?

**Comment by kendagriff** [comment]
The error points to ImageZoom. I suspect it happens upon encountering the first use of `propTypes` or `shape`. Not sure.

I'll try to reproduce it in a project, but I suspect there's some convoluted gnarl in our React app.

**Comment by rpearce** [comment]
@kendagriff Where in `ImageZoom` does the error point to? Line numbers and any details go a long way!

`shape` was my first thought, as well; however, after reading https://github.com/facebook/prop-types/blob/master/README.md, one of their examples uses `shape` like so:
```js
  // An object taking on a particular shape
  optionalObjectWithShape: PropTypes.shape({
    color: PropTypes.string,
    fontSize: PropTypes.number
  }),
```
so I _believe_ that should be fine and working. The fact that this also used in a number of heavily-used production apps without the warning tells me to first explore if this can be re-created in isolation. Fear not!

**Comment by rpearce** [comment]
@kendagriff were you able to reproduce this in another project? If so, I'll look at it immediately. If not, I'd like to close this issue by the end of today. We can totally re-open if there is a reproduce case.

**Comment by kendagriff** [comment]
Feel free to close it—I'll reopen when I have more for you.
