### ISSUE TITLE
Wrap image in link for graceful degradation

### ISSUE THREAD

**Issue by ismay** [rpearce/react-medium-image-zoom#50]
I'm using this library for my portfolio, which is a universal app. Everything works fine, but I recently encountered a bug unrelated to this library which caused my clientside code to fail to boot. Because of the serverside rendering everything still worked, even without clientside js. Except for the zoom that this library provides (which makes sense of course).

Now I definitely don't expect a react app to work without js. But in the spirit of graceful degradation it might be sensible to wrap the image react-medium-image-zoom renders in a link, which points to the zoomImage src. The onClick handler could be attached to the link instead of the image, which would mean that in case of a failure to boot the link would work as a regular link and still lead the user to the zoomed image (albeit without the nice effect etc.).

Just a thought. I'm not sure whether such an implementation would have negative consequences on other parts of this lib. But it seemed like a nice semantic way of adding a bit of graceful degradation. Interested to hear what everyone thinks!

**Comment by rpearce** [comment]
Have you tried having the link  wrapping this component, and onclick your JS prevents default? If it loads the client-side script, then the JS will prevent the link from navigating, and if it doesn't, it'll link where you want (like you said).

At first glance, this doesn't quite feel like it belongs in the lib, as it should just render the image and that's that. 

Are you still seeing a magnify cursor over it? If so, then that would be a small problem and give me cause to consider it or another alternative. 

Open to more thoughts!

**Comment by ismay** [comment]
> Have you tried having the link  wrapping this component, and onclick your JS prevents default? If it loads the client-side script, then the JS will prevent the link from navigating, and if it doesn't, it'll link where you want (like you said).

Nope, I haven't yet tried wrapping it in a link. But I assume that would work. To be honest I'm not sure how I'd pass the click event from the wrapping link on to react-medium-image-zoom. But I'll see what I can come up with, and if I find a working solution I'll post it here for others.

> At first glance, this doesn't quite feel like it belongs in the lib, as it should just render the image and that's that.

Yeah I see what you mean. Focusing on a single thing and doing that well is definitely more important than solving edge cases. The above solution seems better as it could be kept separate from the library.

> Are you still seeing a magnify cursor over it? If so, then that would be a small problem and give me cause to consider it or another alternative.

Yeah. When rendered server side the magnifying icon still shows on hover.

**Comment by ismay** [comment]
> To be honest I'm not sure how I'd pass the click event from the wrapping link on to react-medium-image-zoom.

Ah wait, using isZoomed would probably be the easiest way.

**Comment by rpearce** [comment]
I haven't tried this, but having a simple e.preventDefault() in an onClick handler for your link should do the trick? Here's my reasoning: if your client scripts load, then that link just won't go anywhere, but the image zoom callbacks (which should be ran first) will do their thing regardless. I think this would only get weird if you stopped event bubbling, but even then that's further up the chain so (in theory) would have no effect. 

This is all from my 7:25am brain on the bus. No guarantees yet. 

Give the link with prevent default a go and see what happens!

**Comment by ismay** [comment]
You're right, I was overthinking it, your solution works perfectly. So for others that are trying to do this:

```jsx
<a href="https://image.com/img.jpg" onClick={event => event.preventDefault()}>
  <ImageZoom
    image={{
      src: 'bridge.jpg',
      alt: 'Golden Gate Bridge',
      className: 'img',
      style: { width: '50em' }
    }}
    zoomImage={{
      src: 'bridge-big.jpg',
      alt: 'Golden Gate Bridge'
    }}
  />
</a>
```

When combined with SSR, this'll degrade gracefully for users that have js turned off (or when your app crashes). Instead of zooming it'll link directly to the image and for users with js turned on functionality will be unaffected. Awesome :). Thanks for pointing me in the right direction @rpearce, hope this'll be of help to others!

**Comment by rpearce** [comment]
Always!
