### ISSUE TITLE
ZIndex problem

### ISSUE THREAD

**Issue by leravalera4** [rpearce/react-medium-image-zoom#525]
## Issue Type

- [ ] Bug report
- [ ] Feature request
- [|] Question / support request
- [ ] Other

## Description

![image](https://github.com/rpearce/react-medium-image-zoom/assets/51717886/feaf94a0-38f7-4f5e-9ed4-799af687694c)

I have very big problems with z-index.
Can you please help me?

My modal window has z-index: 1000

And <Zoom zoomZindex={1}> for the images, but it still doesnt work

**Comment by rpearce** [comment]
Closing this until further info is provided. It _feels_ like the project's CSS isn't being used, but we'll see.
