### ISSUE TITLE
React SSR rendering Error 

### ISSUE THREAD

**Issue by draro** [rpearce/react-medium-image-zoom#532]
## Issue Type

- [x] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

## Description
While using SSR Rendering in my React App i get the following Error:
_**Error [ERR_REQUIRE_ESM]: require() of ES Module C:\mypath\node_modules\react-medium-image-zoom\dist\index.js from C:\mypath\index.js not supported.
Instead change the require of C:\mypath\node_modules\react-medium-image-zoom\dist\index.js in C:\mypath\index.js to a dynamic import() which is available in all CommonJS modules.**_

**Comment by rpearce** [comment]
@draro What version are you using? The latest major version is only using esmodules.

**Comment by draro** [comment]
@rpearce , sorry i forgot to add it in the issue:
    "react-medium-image-zoom": "^5.2.0",

**Comment by rpearce** [comment]
@draro This project only exports an ESModule, and it sounds like you're trying to `require('react-medium-image-zoom')` in a CommonJS environment. If that's the case, I don't think there's anything to fix on this side.

I'm going to close this for now, but if you can provide a simple way to reproduce this issue (like an example project or precise steps), I can see what I can do to help.
