### ISSUE TITLE
TODO: react@19 support

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#616]
## Description

This is a TODO for me to ensure this lib has `react@19` support, including allowing it in the `peerDependencies`.

At present, `storybook` is the weak link in the testing chain, as I get errors there. TBD!

**Comment by edlerd** [comment]
Hey there @rpearce 👋 ,

react 19 was released on December 5th, do you need help with an update to reach react 19 support?

**Comment by rpearce** [comment]
Hi! I'm planning on getting to it in the next couple of days, but PRs are welcome!

**Comment by edlerd** [comment]
I opened this one for now: https://github.com/rpearce/react-medium-image-zoom/pull/784

**Comment by rpearce** [comment]
Thanks! I'm hosting a holiday party today and will get to it as soon as I can 🎄

**Comment by rpearce** [comment]
Closed by https://github.com/rpearce/react-medium-image-zoom/pull/784

**Comment by rpearce** [comment]
Confirmed this working here: https://codesandbox.io/p/sandbox/mfwrqh?file=%2Fpackage.json%3A11%2C17
