### ISSUE TITLE
Next js Image problem

### ISSUE THREAD

**Issue by leravalera4** [rpearce/react-medium-image-zoom#667]
## Description

Hi, the Zoom doesnt work with Image tag 
Next js

Is it ok?

Thanks
                                <Zoom zoomZindex={1}>
                                  <div className="zoom-image-container">
                                  <Image
                                    alt="skksks"
                                    src={item.image}
                                    //loading="lazy"
                                    className="product-image"
                                    //aria-hidden="true"
                                  />
                                    </div>
                                </Zoom>

**Comment by rpearce** [comment]
@leravalera4

* Did you make sure to import the CSS file?
* Can you please provide an example that demonstrates this not working?

**Comment by rpearce** [comment]
Closing this due to lack of information.
