### ISSUE TITLE
Enlarge animations on mobile devices

### ISSUE THREAD

**Issue by ompel** [rpearce/react-medium-image-zoom#74]
Looks like the enlarge animations does not work on mobile devices when loading image remotely.
Contract animations works as expected.
On web browsers this works fine.

I'm using this inside a SPA based on react.
This sits inside a <Grid /> component from the 'react-bootstrap' library.
Also tried putting the <ImageZoom /> component alone inside the return of the render function,
Still had that issue.

CODE SAMPLE:

```Javascript
      <div dir="auto">
        <Panel header={<h2>{this.props.dish.name}</h2>}>
        <Grid fluid>
          <Row>
            <Col lg={6} md={6} sm={6} xs={6}>
              <div>
                <ImageZoom
                  image={{
                    src: this.props.dish.image_url,
                    alt: this.props.dish.name,
                    className: 'img-responsive img-rounded',
                    style: { width: '100em' }
                  }}
                  defaultStyles={{
                    overlay: {
                      'backgroundColor': 'rgba(255, 255, 255, 0.8)'
                    },
                    zoomContainer: {
                      zIndex: 9999
                    }
                  }}
                  zoomMargin={10}
                />
              </div>
            </Col>
            <Col lg={6} md={6} sm={6} xs={6}>
              {this.props.dish.description}
            </Col>
          </Row>
          <Row className="price-label">
            <Col>
              <span>{this.props.dish.price_prefix}{this.props.dish.price}</span>
            </Col>
          </Row>
        </Grid>
      </Panel>
    </div>
```

**Comment by rpearce** [comment]
Hi, Omri, and thanks for documenting this here. Can you please provide a live sample of this, as well as what versions you're using of
* this library
* react
* react-dom

I've seen this working on numerous mobile devices last time I checked. Can you please specify what types of mobile devices?

**Comment by ompel** [comment]
Hi,

- this library: 3.0.0
- react: 16.0.0
- react-dom: 16.0.0

Tested on two iPhones(both on Safari and Chrome), LG G3 and a Samsung Galaxy S6

I will try to also provide a video of this behaviour.

**Comment by rpearce** [comment]
@cbothner have you seen this issue?

**Comment by cbothner** [comment]
I’m running with those same versions and seeing no issues on mobile devices. Then I just copied your code sample into a quick create-react-app and unless I'm misunderstanding what issue you’re seeing, it’s working just fine.

**Comment by rpearce** [comment]
@ompel I'm not able to recreate this issue, either. Do you have a small sample project that you can make to recreate this issue?

**Comment by rpearce** [comment]
I'm closing this until we have a way to reproduce this, @ompel. The best way would be to have a small sample project that we can use
