### ISSUE TITLE
Problem shouldReplaceImage 

### ISSUE THREAD

**Issue by alexshelkov** [rpearce/react-medium-image-zoom#89]
I am using 3.0.2, and when I try use **shouldReplaceImage=false** and **zoomImage** together image don't get zoomed second time. 

Expected:

Click to zoom: zoomImage showed.
Click to unzoom: original image showed.

Click to zoom again: zoomImage showed (bit this not works, instead original image showed).

**Comment by rpearce** [comment]
@alexshelkov Thank you for making this report! If you have the time, could you provide a demo of this broken functionality so that it can be effectively debugged?

**Comment by alexshelkov** [comment]
@rpearce ok I prepared small demo for you here: https://alexshelkov.github.io/react-medium-image-zoom/storybook-static/index.html?selectedKind=react-medium-image-zoom&selectedStory=DoubleZoom%20problem&full=1&down=0&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by rpearce** [comment]
@alexshelkov Thanks! I'll check it out this afternoon (New Zealand time), see if I can repro, then work on a fix if so. You rock

**Comment by rpearce** [comment]
Should be fixed in `v3.0.3`

**Comment by rpearce** [comment]
Make that `v3.0.4` (dumb README problem)

**Comment by alexshelkov** [comment]
Thank you! My problem is fixed.
