### ISSUE TITLE
Scrolling to close zoomed image still a tiny bit jumpy at the very end of the animation

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#9]

**Comment by ismay** [comment]
Seems like this is fixed with react@next (v 16). At least for me it is. Woohoo 😄 🎉 🎉 🎉

**Comment by rpearce** [comment]
@ismay do you have a public project where that's the case? If so, can you link it? I sure do like when bugs resolve themselves

**Comment by ismay** [comment]
Not live yet: https://github.com/ismay/ismaywolff.nl/pull/590, still waiting for enzyme support as my tests rely heavily on it. But the build itself works without problems.

**Comment by rpearce** [comment]
Update for posterity: I think this is still a little bit of a thing. It's based on returning the overlayed image back to the _(x,y)_ coordinates that the original one is at before removing the overlay+image from the page, thus making it seem a tiny bit janky. Perhaps investigating [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) could help with it, or some better timing math(s).
