### ISSUE TITLE
Replacing low-res with downloaded high-res image flickers/flashes on new FireFox

### ISSUE THREAD

**Issue by rpearce** [rpearce/react-medium-image-zoom#96]
This issue is a: 

- Bug report

## Expected behavior
I expected there to not be a flicker when the the larger image was loaded and replaced the old one.

## Actual behavior
What actually happened: it flickers.

## Steps to reproduce behavior
1. open up the new firefox
1. go to the example page (link below)
1. click the first image (a bridge)

## Link to repository/example of behavior
[link to example](https://rpearce.github.io/react-medium-image-zoom/)

**Comment by kingdido999** [comment]
I have encountered the exact issue before and fixed it by force computing the hi-res image in DOM: kingdido999/zooming#7. Hope it helps.

**Comment by rpearce** [comment]
@kingdido999 Thanks for sharing! I'll check it out ASAP
